{
 "title": "Kafka Consumer - v2",
 "description": "Overview of the Kafka consumers",
 "tags": [
  "confluent",
  "kafka-client",
  "kafka-consumer"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": "label_values(env)" },
   {
    "name": "server",
    "label": "Server",
    "query": "label_values(kafka_consumer_consumer_metrics_incoming_byte_rate{env=\"$env\", client_type=\"consumer\"},hostname)"
   },
   {
    "name": "client_id",
    "label": "Client ID",
    "query": "label_values(kafka_consumer_consumer_metrics_incoming_byte_rate{env=\"$env\", client_type=\"consumer\"},client_id)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Record Consumed Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(10, kafka_consumer_consumer_fetch_manager_metrics_records_consumed_rate{env=\"$env\", client_type=\"producer\", client_id=~\"$client_id\", hostname=~\"$server\"} > 0)",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Records Lag",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(10, kafka_consumer_consumer_fetch_manager_metrics_records_consumed_rate{env=\"$env\", client_type=\"producer\", client_id=~\"$client_id\", hostname=~\"$server\"} > 0)",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Last Rebalance Seconds Ago",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(10, kafka_consumer_consumer_coordinator_metrics_last_rebalance_seconds_ago{env=\"$env\", client_type=\"producer\", client_id=~\"$client_id\", hostname=~\"$server\"} > 0)",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Versions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kafka_consumer_app_info{env=\"$env\", client_id=~\"$client_id\", version!=\"\", hostname=~\"$server\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes Consumed Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk(10,kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_rate{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}}"
      }
     ]
    },
    {
     "title": "Records Consumed Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "cts" } },
     "targets": [
      {
       "expr": "topk(10,kafka_consumer_consumer_fetch_manager_metrics_records_consumed_rate{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}}"
      }
     ]
    },
    {
     "title": "Records Lag Max",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
     "targets": [
      {
       "expr": "topk(10,kafka_consumer_consumer_fetch_manager_metrics_records_lag_max{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}}"
      }
     ]
    },
    {
     "title": "Fetch Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "topk(10,kafka_consumer_consumer_fetch_manager_metrics_fetch_rate{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}}"
      }
     ]
    },
    {
     "title": "Fetch Latency",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 2 },
     "targets": [
      {
       "expr": "topk(10,kafka_consumer_consumer_fetch_manager_metrics_fetch_latency_avg{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}} (avg.)"
      },
      {
       "expr": "topk(10,kafka_consumer_consumer_fetch_manager_metrics_fetch_latency_max{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}} (max.)"
      }
     ]
    },
    {
     "title": "Fetch Size",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 2 },
     "targets": [
      {
       "expr": "topk(10,kafka_consumer_consumer_fetch_manager_metrics_fetch_size_avg{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}} (avg.)"
      },
      {
       "expr": "topk(10,kafka_consumer_consumer_fetch_manager_metrics_fetch_size_max{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}} (max.)"
      }
     ]
    },
    {
     "title": "Fetch Throttle Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "topk(10,kafka_consumer_consumer_fetch_manager_metrics_fetch_throttle_time_avg{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}} (avg.)"
      },
      {
       "expr": "topk(10,kafka_consumer_consumer_fetch_manager_metrics_fetch_throttle_time_max{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}} (max.)"
      }
     ]
    },
    {
     "title": "Records per Request Avg.",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 3 },
     "targets": [
      {
       "expr": "topk(10,kafka_consumer_consumer_fetch_manager_metrics_fetch_records_per_request_avg{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consumer group",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Commit Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "topk(10,kafka_consumer_consumer_coordinator_metrics_commit_rate{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}}"
      }
     ]
    },
    {
     "title": "Join Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
     "targets": [
      {
       "expr": "topk(10,kafka_consumer_consumer_coordinator_metrics_join_rate{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}}"
      }
     ]
    },
    {
     "title": "Sync Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
     "targets": [
      {
       "expr": "topk(10,kafka_consumer_consumer_coordinator_metrics_sync_rate{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}}"
      }
     ]
    },
    {
     "title": "Commit Latency",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "topk(10,kafka_consumer_consumer_coordinator_metrics_commit_latency_avg{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}} (avg.)"
      },
      {
       "expr": "topk(10,kafka_consumer_consumer_coordinator_metrics_commit_latency_max{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}} (max.)"
      }
     ]
    },
    {
     "title": "Join Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "topk(10,kafka_consumer_consumer_coordinator_metrics_join_time_avg{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}} (avg.)"
      },
      {
       "expr": "topk(10,kafka_consumer_consumer_coordinator_metrics_join_time_max{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}} (max.)"
      }
     ]
    },
    {
     "title": "Sync Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "topk(10,kafka_consumer_consumer_coordinator_metrics_sync_time_avg{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}} (avg.)"
      },
      {
       "expr": "topk(10,kafka_consumer_consumer_coordinator_metrics_sync_time_max{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}} (max.)"
      }
     ]
    },
    {
     "title": "Heartbeat Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "topk(10,kafka_consumer_consumer_coordinator_metrics_heartbeat_rate{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}}"
      }
     ]
    },
    {
     "title": "Heartbeat Response Time (Max.)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "topk(10,kafka_consumer_consumer_coordinator_metrics_heartbeat_response_time_max{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}}"
      }
     ]
    },
    {
     "title": "Last Heartbeat Seconds Ago",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(10,kafka_consumer_consumer_coordinator_metrics_last_heartbeat_seconds_ago{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}}"
      }
     ]
    },
    {
     "title": "Assigned Partitions",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "topk(10,kafka_consumer_consumer_coordinator_metrics_assigned_partitions{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connection Count",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "topk(10,kafka_consumer_consumer_metrics_connection_count{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}}"
      }
     ]
    },
    {
     "title": "Connection Creation Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "topk(10,kafka_consumer_consumer_metrics_connection_creation_rate{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}}"
      }
     ]
    },
    {
     "title": "Connection Close Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "topk(10,kafka_consumer_consumer_metrics_connection_close_rate{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}}"
      }
     ]
    },
    {
     "title": "IO ratio",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "topk(10,kafka_consumer_consumer_metrics_io_ratio{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}}"
      }
     ]
    },
    {
     "title": "IO wait ratio",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 9 },
     "targets": [
      {
       "expr": "topk(10,kafka_consumer_consumer_metrics_io_wait_ratio{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}}"
      }
     ]
    },
    {
     "title": "Select Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "topk(10,kafka_consumer_consumer_metrics_select_rate{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}}"
      }
     ]
    },
    {
     "title": "IO time avg.",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "topk(10,kafka_consumer_consumer_metrics_io_time_ns_avg{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}}"
      }
     ]
    },
    {
     "title": "IO wait time avg.",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "topk(10,kafka_consumer_consumer_metrics_io_wait_time_ns_avg{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Per Broker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Incoming Byte Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk(10,kafka_consumer_consumer_node_metrics_incoming_byte_rate{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}} <- {{node_id}}"
      }
     ]
    },
    {
     "title": "Outgoing Byte Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk(10,kafka_consumer_consumer_node_metrics_outgoing_byte_rate{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}} -> {{node_id}}"
      }
     ]
    },
    {
     "title": "Request Latency",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "topk(10,kafka_consumer_consumer_node_metrics_request_latency_avg{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}} -> {{node_id}} (avg.)"
      },
      {
       "expr": "topk(10,kafka_consumer_consumer_node_metrics_request_latency_max{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}} -> {{node_id}} (max.)"
      }
     ]
    },
    {
     "title": "Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "topk(10,kafka_consumer_consumer_node_metrics_request_rate{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}} -> {{node_id}}"
      }
     ]
    },
    {
     "title": "Response Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "topk(10,kafka_consumer_consumer_node_metrics_response_rate{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}} <- {{node_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Per Topic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes Consumed Rate per Topic",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk(10,kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_rate{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}} <- {{topic}}"
      }
     ]
    },
    {
     "title": "Records Consumed Rate per Topic",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "topk(10,kafka_consumer_consumer_fetch_manager_metrics_records_consumed_rate{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}} <- {{topic}}"
      }
     ]
    },
    {
     "title": "Fetch Size per Topic",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(10,kafka_consumer_consumer_fetch_manager_metrics_fetch_size_avg{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}} <- {{topic}} (avg.)"
      },
      {
       "expr": "topk(10,kafka_consumer_consumer_fetch_manager_metrics_fetch_size_max{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}} <- {{topic}} (max.)"
      }
     ]
    },
    {
     "title": "Records per Request Avg. per Topic",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
     "targets": [
      {
       "expr": "topk(10,kafka_consumer_consumer_fetch_manager_metrics_records_per_request_avg{env=\"$env\",client_id=~\"$client_id\", hostname=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{hostname}} <- {{topic}}"
      }
     ]
    }
   ]
  }
 ]
}