{
 "title": "Kafka cluster - v2",
 "description": "Overview of the Kafka cluster",
 "tags": [
  "confluent",
  "kafka"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": "label_values(env)" },
   {
    "name": "broker",
    "label": "Broker",
    "query": "label_values(kafka_server_replicamanager_leadercount{env=\"$env\"}, hostname)"
   },
   {
    "name": "quantile",
    "label": "Quantile",
    "query": "label_values(kafka_network_requestmetrics_requestqueuetimems{env=\"$env\"}, quantile)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kafka: Online Brokers",
   "type": "stat",
   "description": "Count of brokers available (online).\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount{env=\"$env\"})"
    }
   ]
  },
  {
   "title": "Kafka: Active Controller",
   "type": "stat",
   "description": "Active Controller broker.\n            It should always be 1. If the value is different than 1, then it must be alerted for troubleshooting.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount{env=\"$env\"} > 0",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Kafka: Sum of Preferred Replica Imbalance",
   "type": "stat",
   "description": "\n            Number of partitions where the preferred replica is not the leader.\n            Usually, this number is 0.\n            Restarting nodes could cause this values to change, but when reassigning happens the value stabilize.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_preferredreplicaimbalancecount{env=\"$env\"})"
    }
   ]
  },
  {
   "title": "Kafka: Sum of Topics",
   "type": "stat",
   "description": "Number of topics in the cluster.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_globaltopiccount{env=\"$env\"})"
    }
   ]
  },
  {
   "title": "Kafka: Rate of Requests/Sec",
   "type": "stat",
   "description": "Sum of requests per second rated over a 5 min. period.\n            Gives an idea of the processing load in the cluster.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_requestspersec{env=\"$env\",hostname=~\"$broker\"}[5m]))"
    }
   ]
  },
  {
   "title": "Kafka: Log Size",
   "type": "stat",
   "description": "Sum of log sizes per broker.\n            This must be compared with the total storage space available in the brokers.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_log_log_size{env=\"$env\",hostname=~\"$broker\"}) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Kafka: Sum of Partitions",
   "type": "stat",
   "description": "Sum of Topic partitions across the cluster.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount{env=\"$env\",hostname=~\"$broker\"})"
    }
   ]
  },
  {
   "title": "Kafka: Sum of Under-Replicated Partitions (URP)",
   "type": "stat",
   "description": "Sum of Under-Replicated Partitions. This is caused by broker or volumes unavailable, impacting replicas to be offline, and reducing the ISR set for those partitions.\n            There are transient scenarios that could lead to this number growing (e.g. broker restart), but if the number doesn't shrink in a short period of time (e.g. 1 minute), then it's recommended to alert.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions{env=\"$env\",hostname=~\"$broker\"})"
    }
   ]
  },
  {
   "title": "Kafka: Sum of Under-MinISR Partitions",
   "type": "stat",
   "description": "Number of partitions where the number of replicas offline is higher than the minimum ISR configuration.\n            This means partitions are not available for Producers with acks=all.\n            We recommend alerting when this values is higher than 0.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underminisr{env=\"$env\",hostname=~\"$broker\"})"
    }
   ]
  },
  {
   "title": "Kafka: Sum of Offline Partitions",
   "type": "stat",
   "description": "Number of partitions where all replicas are offline.\n            Producers and Consumers are affected by this condition.\n            We recommend alerting when this values is higher than 0.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{env=\"$env\",hostname=~\"$broker\"})"
    }
   ]
  },
  {
   "title": "Kafka: Bytes In/Sec",
   "type": "stat",
   "description": "Sum of bytes in per second rated over a 5 min. period.\n            Gives an idea of the incoming throughput handle by the cluster.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesinpersec{env=\"$env\",hostname=~\"$broker\"}[5m]))"
    }
   ]
  },
  {
   "title": "Kafka: Bytes Out/Sec",
   "type": "stat",
   "description": "Sum of bytes out per second rated over a 5 min. period.\n            Gives an idea of the outgoing throughput handle by the cluster.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesoutpersec{env=\"$env\",hostname=~\"$broker\"}[5m]))"
    }
   ]
  },
  { "title": "System resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "Rate of CPU seconds used by the Java process.\n            100% usage represents one core. \n            If there are multiple cores, the total capacity should be 100% * number_cores.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{env=\"$env\",hostname=~\"$broker\"}[5m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Sum of JVM memory used, without including areas (e.g. heap size).",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{env=\"$env\",hostname=~\"$broker\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "GC collection",
   "type": "timeseries",
   "description": "Sum of seconds used by Garbage Collection.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(gc)(irate(jvm_gc_collection_seconds_sum{env=\"$env\",hostname=~\"$broker\"}[5m]))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages In/Sec",
     "type": "timeseries",
     "description": "Number of messages into topics per second, aggregated by sum without topic.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum without(topic) (rate(kafka_server_brokertopicmetrics_messagesinpersec{env=\"$env\",hostname=~\"$broker\"}[5m]))",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Bytes In/Sec",
     "type": "timeseries",
     "description": "Number of bytes into topics per second, aggregated by sum without topic.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum without(topic) (rate(kafka_server_brokertopicmetrics_bytesinpersec{env=\"$env\",hostname=~\"$broker\"}[5m]))",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Bytes Out/Sec",
     "type": "timeseries",
     "description": "Number of bytes out of topics per second, aggregated by sum without topic.",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum without(topic) (rate(kafka_server_brokertopicmetrics_bytesoutpersec{env=\"$env\",hostname=~\"$broker\"}[5m]))",
       "legendFormat": "{{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Thread utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network processor usage",
     "type": "timeseries",
     "description": "Percent of time the network thread pool is used.\n            It should be below 60% or the capacity of threads should be tuned or \n            the cluster scaled to cope with the load.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1-kafka_network_socketserver_networkprocessoravgidlepercent{env=\"$env\",hostname=~\"$broker\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Request processor (IO) usage",
     "type": "timeseries",
     "description": "Percent of time the IO thread pool is used.\n            It should be below 60% or the capacity of threads should be tuned or \n            the cluster scaled to cope with the load.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1-kafka_server_kafkarequesthandlerpool_requesthandleravgidlepercent_total{env=\"$env\",hostname=~\"$broker\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Request rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests rates",
     "type": "timeseries",
     "description": "Requests per second rated over a 5 minutes period.\n            Includes API call and version.\n            ",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum without(pod,instance,statefulset_kubernetes_io_pod_name)(rate(kafka_network_requestmetrics_requestspersec{env=\"$env\",hostname=~\"$broker\"}[5m]))",
       "legendFormat": "{{request}}(v{{version}})"
      }
     ]
    },
    {
     "title": "Error rates",
     "type": "timeseries",
     "description": "Request Errors per second rated over a 5 minutes period.\n            Includes API call and version.\n            ",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum without(pod,instance,statefulset_kubernetes_io_pod_name)(rate(kafka_network_requestmetrics_errorspersec{env=\"$env\",hostname=~\"$broker\",error!=\"NONE\"}[5m]))",
       "legendFormat": "{{error}}@{{request}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sum of Connections alive per Broker",
     "type": "timeseries",
     "description": "Sum of connections count across cluster by brokers",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "sum(kafka_server_socketservermetrics_connection_count{env=\"$env\",hostname=~\"$broker\"}) by (hostname)",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Sum of Connections creation rate per Broker",
     "type": "timeseries",
     "description": "Sum of rate of connections created across cluster by brokers",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 6 },
     "targets": [
      {
       "expr": "sum(kafka_server_socketservermetrics_connection_creation_rate{env=\"$env\",hostname=~\"$broker\"}) by (hostname)",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Sum of Connections close rate per Broker",
     "type": "timeseries",
     "description": "Sum of rate of connections closed across cluster by brokers",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 6 },
     "targets": [
      {
       "expr": "sum(kafka_server_socketservermetrics_connection_close_rate{env=\"$env\",hostname=~\"$broker\"}) by (hostname)",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Sum of Connections alive per Listener",
     "type": "timeseries",
     "description": "Sum of connections count across cluster by listeners",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum(kafka_server_socketservermetrics_connection_count{env=\"$env\",hostname=~\"$broker\"}) by (listener)",
       "legendFormat": "{{listener}}"
      }
     ]
    },
    {
     "title": "Sum of Connections creation rate per Listener",
     "type": "timeseries",
     "description": "Sum of rate of connections created across cluster by listener",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 7 },
     "targets": [
      {
       "expr": "sum(kafka_server_socketservermetrics_connection_creation_rate{env=\"$env\",hostname=~\"$broker\"}) by (listener)",
       "legendFormat": "{{listener}}"
      }
     ]
    },
    {
     "title": "Sum of Connections close rate per Listener",
     "type": "timeseries",
     "description": "Sum of rate of connections closed across cluster by listener",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 7 },
     "targets": [
      {
       "expr": "sum(kafka_server_socketservermetrics_connection_close_rate{env=\"$env\",hostname=~\"$broker\"}) by (listener)",
       "legendFormat": "{{listener}}"
      }
     ]
    }
   ]
  },
  {
   "title": "In-Sync Replicas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate of ISR Shrinks/sec",
     "type": "timeseries",
     "description": "Rate of ISR shrinks per second.\n            If this value is continuously higher than 0, then troubleshoot cause of ISR changing constantly.\n            ",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "rate(kafka_server_replicamanager_isrshrinkspersec{env=\"$env\",hostname=~\"$broker\"}[5m])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Rate of ISR Expands/sec",
     "type": "timeseries",
     "description": "Rate of ISR expands per second.\n            If this value is continuously higher than 0, then troubleshoot cause of ISR changing constantly.\n            ",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 8 },
     "targets": [
      {
       "expr": "rate(kafka_server_replicamanager_isrexpandspersec{env=\"$env\",hostname=~\"$broker\"}[5m])",
       "legendFormat": "{{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Request latency: Producer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Produce: Request Queue Time",
     "type": "timeseries",
     "description": "Time expend on the request queue.\n            Moved from network socket to request queue by Network threads.\n            ",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_requestqueuetimems{env=\"$env\",hostname=~\"$broker\",quantile=~\"$quantile\",request=\"Produce\"}",
       "legendFormat": "{{hostname}} ({{quantile}}th)"
      }
     ]
    },
    {
     "title": "Produce: Local Time",
     "type": "timeseries",
     "description": "Time expend doing local IO.\n            Moved from request queue to storage device operations by IO threads.\n            ",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_localtimems{env=\"$env\",hostname=~\"$broker\",quantile=~\"$quantile\",request=\"Produce\"}",
       "legendFormat": "{{hostname}} ({{quantile}}th)"
      }
     ]
    },
    {
     "title": "Produce: Remote Time",
     "type": "timeseries",
     "description": "Time expend waiting for coordination with other brokers/internal condition.\n            At purgatory.\n            ",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_remotetimems{env=\"$env\",hostname=~\"$broker\",quantile=~\"$quantile\",request=\"Produce\"}",
       "legendFormat": "{{hostname}} ({{quantile}}th)"
      }
     ]
    },
    {
     "title": "Produce: Response Queue Time",
     "type": "timeseries",
     "description": "Time expend waiting in response queue.\n            Moved from purgatory to response queue by IO threads.\n            ",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_responsequeuetimems{env=\"$env\",hostname=~\"$broker\",quantile=~\"$quantile\",request=\"Produce\"}",
       "legendFormat": "{{hostname}} ({{quantile}}th)"
      }
     ]
    },
    {
     "title": "Produce: Response Send Time",
     "type": "timeseries",
     "description": "Time expend delivering response.\n            Moved from response queue to client by Networkc threads.\n            ",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_responsesendtimems{env=\"$env\",hostname=~\"$broker\",quantile=~\"$quantile\",request=\"Produce\"}",
       "legendFormat": "{{hostname}} ({{quantile}}th)"
      }
     ]
    }
   ]
  },
  {
   "title": "Request latency: Consumer Fetch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fetch: Request Queue Time",
     "type": "timeseries",
     "description": "Time expend on the request queue.\n            Moved from network socket to request queue by Network threads.\n            ",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_requestqueuetimems{env=\"$env\",hostname=~\"$broker\",quantile=~\"$quantile\",request=\"Fetch\"}",
       "legendFormat": "{{hostname}} ({{quantile}}th)"
      }
     ]
    },
    {
     "title": "Fetch: Local Time",
     "type": "timeseries",
     "description": "Time expend doing local IO.\n            Moved from request queue to storage device operations by IO threads.\n            ",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_localtimems{env=\"$env\",hostname=~\"$broker\",quantile=~\"$quantile\",request=\"Fetch\"}",
       "legendFormat": "{{hostname}} ({{quantile}}th)"
      }
     ]
    },
    {
     "title": "Fetch: Remote Time",
     "type": "timeseries",
     "description": "Time expend waiting for coordination with other brokers/internal condition.\n            At purgatory.\n            ",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_remotetimems{env=\"$env\",hostname=~\"$broker\",quantile=~\"$quantile\",request=\"Fetch\"}",
       "legendFormat": "{{hostname}} ({{quantile}}th)"
      }
     ]
    },
    {
     "title": "Fetch: Response Queue Time",
     "type": "timeseries",
     "description": "Time expend waiting in response queue.\n            Moved from purgatory to response queue by IO threads.\n            ",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_responsequeuetimems{env=\"$env\",hostname=~\"$broker\",quantile=~\"$quantile\",request=\"Fetch\"}",
       "legendFormat": "{{hostname}} ({{quantile}}th)"
      }
     ]
    },
    {
     "title": "Fetch: Response Send Time",
     "type": "timeseries",
     "description": "Time expend delivering response.\n            Moved from response queue to client by Networkc threads.\n            ",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_responsesendtimems{env=\"$env\",hostname=~\"$broker\",quantile=~\"$quantile\",request=\"Fetch\"}",
       "legendFormat": "{{hostname}} ({{quantile}}th)"
      }
     ]
    }
   ]
  },
  {
   "title": "Request latency: Replica Fetch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fetch: Request Queue Time",
     "type": "timeseries",
     "description": "Time expend on the request queue.\n            Moved from network socket to request queue by Network threads.\n            ",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_requestqueuetimems{env=\"$env\",hostname=~\"$broker\",quantile=~\"$quantile\",request=\"FetchFollower\"}",
       "legendFormat": "{{hostname}} ({{quantile}}th)"
      }
     ]
    },
    {
     "title": "Fetch: Local Time",
     "type": "timeseries",
     "description": "Time expend doing local IO.\n            Moved from request queue to storage device operations by IO threads.\n            ",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_localtimems{env=\"$env\",hostname=~\"$broker\",quantile=~\"$quantile\",request=\"FetchFollower\"}",
       "legendFormat": "{{hostname}} ({{quantile}}th)"
      }
     ]
    },
    {
     "title": "Fetch: Remote Time",
     "type": "timeseries",
     "description": "Time expend waiting for coordination with other brokers/internal condition.\n            At purgatory.\n            ",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_remotetimems{env=\"$env\",hostname=~\"$broker\",quantile=~\"$quantile\",request=\"FetchFollower\"}",
       "legendFormat": "{{hostname}} ({{quantile}}th)"
      }
     ]
    },
    {
     "title": "Fetch: Response Queue Time",
     "type": "timeseries",
     "description": "Time expend waiting in response queue.\n            Moved from purgatory to response queue by IO threads.\n            ",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_responsequeuetimems{env=\"$env\",hostname=~\"$broker\",quantile=~\"$quantile\",request=\"FetchFollower\"}",
       "legendFormat": "{{hostname}} ({{quantile}}th)"
      }
     ]
    },
    {
     "title": "Fetch: Response Send Time",
     "type": "timeseries",
     "description": "Time expend delivering response.\n            Moved from response queue to client by Networkc threads.\n            ",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_responsesendtimems{env=\"$env\",hostname=~\"$broker\",quantile=~\"$quantile\",request=\"FetchFollower\"}",
       "legendFormat": "{{hostname}} ({{quantile}}th)"
      }
     ]
    }
   ]
  },
  {
   "title": "Group Coordinator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Groups per Broker",
     "type": "timeseries",
     "description": "Number of groups managed by Broker",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "kafka_coordinator_group_groupmetadatamanager_numgroups{env=\"$env\",hostname=~\"$broker\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Number of Groups per Broker per Status",
     "type": "timeseries",
     "description": "Number of stable groups managed by Broker",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 15 },
     "targets": [
      {
       "expr": "sum(kafka_coordinator_group_groupmetadatamanager_numgroupsstable{env=\"$env\",hostname=~\"$broker\"})",
       "legendFormat": "stable"
      },
      {
       "expr": "sum(kafka_coordinator_group_groupmetadatamanager_numgroupspreparingrebalance{env=\"$env\",hostname=~\"$broker\"})",
       "legendFormat": "preparing_rebalance"
      },
      {
       "expr": "sum(kafka_coordinator_group_groupmetadatamanager_numgroupsdead{env=\"$env\",hostname=~\"$broker\"})",
       "legendFormat": "dead"
      },
      {
       "expr": "sum(kafka_coordinator_group_groupmetadatamanager_numgroupscompletingrebalance{env=\"$env\",hostname=~\"$broker\"})",
       "legendFormat": "completing_rebalance"
      },
      {
       "expr": "sum(kafka_coordinator_group_groupmetadatamanager_numgroupsempty{env=\"$env\",hostname=~\"$broker\"})",
       "legendFormat": "empty"
      }
     ]
    }
   ]
  },
  {
   "title": "Message Conversion",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sum of Produce conversion rate per sec",
     "type": "timeseries",
     "description": "Sum of produce message conversions per second.\n            This value increases when the broker receives produce messages from clients using older versions.\n            ",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "opsps" } },
     "targets": [
      {
       "expr": "sum(kafka_server_brokertopicmetrics_producemessageconversionspersec{env=\"$env\",hostname=~\"$broker\"})",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Sum of Fetch conversion rate per sec",
     "type": "timeseries",
     "description": "Sum of fetch message conversions per second.\n            This value increases when the broker receives fetch messages from clients using older versions.\n            ",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "opsps" } },
     "targets": [
      {
       "expr": "sum(kafka_server_brokertopicmetrics_fetchmessageconversionspersec{env=\"$env\",hostname=~\"$broker\"})",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Sum of Connections per version",
     "type": "timeseries",
     "description": "Sum of connections aggregated by client version and name.\n            ",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 16 },
     "targets": [
      {
       "expr": "sum(kafka_server_socketservermetrics_connections{env=\"$env\",hostname=~\"$broker\"}) by (client_software_name,client_software_version)",
       "legendFormat": "{{client_software_name}} (v{{client_software_version}})"
      }
     ]
    }
   ]
  }
 ]
}