{
 "title": "Kafka topics - v2",
 "description": "Overview of the Kafka topics",
 "tags": [
  "confluent",
  "kafka"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": "label_values(env)" },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_log_log_size{env=\"$env\"}, topic)"
   }
  ]
 },
 "panels": [
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Messages In/Sec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "topk(10, sum without(instance,pod,statefulset_kubernetes_io_pod_name) (rate(kafka_server_brokertopicmetrics_messagesinpersec{topic=~\"$topic\",env=\"$env\"}[5m])))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Log size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, sum(kafka_log_log_size{env=\"$env\",topic=~\"$topic\"}) by (topic))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In/Sec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(10, sum without(instance,pod,statefulset_kubernetes_io_pod_name) (rate(kafka_server_brokertopicmetrics_bytesinpersec{topic=~\"$topic\",env=\"$env\"}[5m])))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out/Sec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(10, sum without(instance,pod,statefulset_kubernetes_io_pod_name) (rate(kafka_server_brokertopicmetrics_bytesoutpersec{topic=~\"$topic\",env=\"$env\"}[5m])))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Produce Requests/Sec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(kafka_server_brokertopicmetrics_totalproducerequestspersec{ env=\"$env\", topic=~\"$topic\"}[5m])) by (topic))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer Fetch Requests/Sec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(kafka_server_brokertopicmetrics_totalfetchrequestspersec{ env=\"$env\", topic=~\"$topic\"}[5m])) by (topic))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Offsets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Start Offsets",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "kafka_log_log_logstartoffset{env=\"$env\",topic=~\"$topic\"}",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "End Offsets",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "kafka_log_log_logendoffset{env=\"$env\",topic=~\"$topic\"}",
       "legendFormat": "{{topic}}"
      }
     ]
    }
   ]
  }
 ]
}