{
 "title": "Confluent Platform overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ns", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "kafka_connect_app",
    "label": "Connect cluster",
    "query": {
     "query": "label_values(kafka_connect_connect_worker_metrics_connector_count{namespace=\"$ns\"}, app)"
    }
   },
   {
    "name": "ksqldb_cluster_id",
    "label": "ksqlDB Cluster ID",
    "query": {
     "query": "label_values(ksql_ksql_engine_query_stats_liveness_indicator{namespace=\"$ns\"},ksql_cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Zookeeper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Zookeeper nodes online",
   "type": "stat",
   "description": "Quorum Size of Zookeeper ensemble",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(zookeeper_status_quorumsize{namespace=\"$ns\"})"
    }
   ]
  },
  {
   "title": "Number of ZNodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(zookeeper_inmemorydatatree_nodecount{namespace=\"$ns\"})"
    }
   ]
  },
  {
   "title": "Alive Connections",
   "type": "stat",
   "description": "Number of Alive Connections",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(zookeeper_numaliveconnections{namespace=\"$ns\"})"
    }
   ]
  },
  {
   "title": "Number of Watchers",
   "type": "stat",
   "description": "Number of Watchers",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(zookeeper_inmemorydatatree_watchcount{namespace=\"$ns\"})"
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "stat",
   "description": "Number of Alive Connections",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zookeeper_outstandingrequests{namespace=\"$ns\"}",
     "legendFormat": "{{pod}} ({{member_type}})"
    }
   ]
  },
  { "title": "Kafka Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Active Controllers",
   "type": "stat",
   "description": "Number of active controllers in the cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount{namespace=\"$ns\"} > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Brokers Online",
   "type": "stat",
   "description": "Number of Brokers Online",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount{namespace=\"$ns\"})"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "stat",
   "description": "Partitions that are online",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount{namespace=\"$ns\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "description": "Number of under-replicated partitions (| ISR | < | all replicas |).",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions{namespace=\"$ns\"})"
    }
   ]
  },
  {
   "title": "Under Min ISR Partitions",
   "type": "stat",
   "description": "Number of partitions under min insync replicas.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underminisr{namespace=\"$ns\"})"
    }
   ]
  },
  {
   "title": "Offline Partitions Count",
   "type": "stat",
   "description": "Number of partitions that dont have an active leader and are hence not writable or readable.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{namespace=\"$ns\"})"
    }
   ]
  },
  { "title": "Shema Registry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Schema Registry Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kafka_schema_registry_registered_count{namespace=\"$ns\"})"
    }
   ]
  },
  {
   "title": "Schemas registered",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_schema_registry_registered_count{namespace=\"$ns\"})"
    }
   ]
  },
  {
   "title": "Schemas deleted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_schema_registry_schemas_deleted{namespace=\"$ns\"})"
    }
   ]
  },
  {
   "title": "Kafka Connect ($kafka_connect_app) ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "repeat": "cluster"
  },
  {
   "title": "Connect worker instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kafka_connect_connect_worker_metrics_connector_count{namespace=\"$ns\",app=~\"$kafka_connect_app\"})"
    }
   ]
  },
  {
   "title": "Tasks Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_total_task_count{namespace=\"$ns\",app=~\"$kafka_connect_app\"})"
    }
   ]
  },
  {
   "title": "Tasks Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_running_task_count{namespace=\"$ns\",app=~\"$kafka_connect_app\"})"
    }
   ]
  },
  {
   "title": "Tasks Paused",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_paused_task_count{namespace=\"$ns\",instance=~\"$instance\",app=~\"$kafka_connect_app\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_failed_task_count{namespace=\"$ns\",instance=~\"$instance\",app=~\"$kafka_connect_app\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Time since last rebalance ",
   "type": "stat",
   "description": "Time since last rebalance",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "clockms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_rebalance_metrics_time_since_last_rebalance_ms{namespace=\"$ns\",app=~\"$kafka_connect_app\"} >= 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ksqlDB Cluster ($ksqldb_cluster_id) ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "repeat": "clusterid"
  },
  {
   "title": "ksqlDB instances",
   "type": "stat",
   "description": "Average number of active queries per server.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ksql_ksql_engine_query_stats_num_active_queries{namespace=\"$ns\", ksql_cluster=\"$ksqldb_cluster_id\"})"
    }
   ]
  },
  {
   "title": "Active Queries",
   "type": "stat",
   "description": "Average number of active queries per server.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ksql_ksql_engine_query_stats_num_active_queries{namespace=\"$ns\", ksql_cluster=\"$ksqldb_cluster_id\"})"
    }
   ]
  },
  {
   "title": "Running Queries",
   "type": "stat",
   "description": "Num of created queries",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ksql_ksql_engine_query_stats_running_queries{namespace=\"$ns\", ksql_cluster=\"$ksqldb_cluster_id\"})"
    }
   ]
  },
  {
   "title": "Rebalancing Queries",
   "type": "stat",
   "description": "Num of rebalancing queries",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ksql_ksql_engine_query_stats_rebalancing_queries{namespace=\"$ns\", ksql_cluster=\"$ksqldb_cluster_id\"})"
    }
   ]
  },
  {
   "title": "Queries in Error State",
   "type": "stat",
   "description": "Number of error query",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ksql_ksql_engine_query_stats_error_queries{namespace=\"$ns\", ksql_cluster=\"$ksqldb_cluster_id\"})"
    }
   ]
  },
  {
   "title": "Stopped Queries",
   "type": "stat",
   "description": "Num of not running queries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ksql_ksql_engine_query_stats_not_running_queries{namespace=\"$ns\", ksql_cluster=\"$ksqldb_cluster_id\"})"
    }
   ]
  }
 ]
}