{
 "title": "ksqlDB cluster - v2",
 "description": "Overview of ksqlDB clusters.",
 "tags": [
  "confluent",
  "ksqldb"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": "label_values(namespace)" },
   {
    "name": "ksqldb_cluster",
    "label": "ksqlDB cluster",
    "query": "label_values(ksql_ksql_engine_query_stats_num_active_queries{namespace=\"$env\"},app)"
   },
   {
    "name": "ksqldb_cluster_id",
    "label": "ksqlDB cluster ID",
    "query": "label_values(ksql_ksql_engine_query_stats_num_active_queries{namespace=\"$env\"},ksql_cluster)"
   },
   {
    "name": "ksqldb_server",
    "label": "ksqlDB server",
    "query": "label_values(ksql_ksql_engine_query_stats_num_active_queries{namespace=\"$env\",app=\"$ksqldb_cluster\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ksqlDB: Online Servers",
   "type": "stat",
   "description": "ksqlDB online instances returning metrics.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ksql_ksql_engine_query_stats_num_active_queries{namespace=\"$env\", app=\"$ksqldb_cluster\"})"
    }
   ]
  },
  {
   "title": "ksqlDB: Sum of Active Queries",
   "type": "stat",
   "description": "Number of active queries deployed in the cluster.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ksql_ksql_engine_query_stats_num_active_queries{namespace=\"$env\", app=\"$ksqldb_cluster\"})"
    }
   ]
  },
  {
   "title": "ksqlDB: Sum of Running Queries",
   "type": "stat",
   "description": "Number of running queries deployed in the cluster.\n            Ideally, this number should be equal to the number of active queries as queries should be running.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ksql_ksql_engine_query_stats_running_queries{namespace=\"$env\", app=\"$ksqldb_cluster\"})"
    }
   ]
  },
  {
   "title": "ksqlDB: Sum of Rebalancing Queries",
   "type": "stat",
   "description": "Number of queries rebalancing in the cluster.\n            Ideally, this number should be equal zero, or return to zero in a short period (e.g. 1 minute).\n            It's recommended to alert if the number of rebalancing queries stay higher than 0 for a longer period of time.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ksql_ksql_engine_query_stats_rebalancing_queries{namespace=\"$env\", app=\"$ksqldb_cluster\"})"
    }
   ]
  },
  {
   "title": "Connect: Sum of Queries Failed",
   "type": "stat",
   "description": "Number of queries failed in the cluster.\n            Ideally, this number should be equal zero.\n            It's recommended to alert if the number of queries failed is higher than 0.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(ksql_ksql_engine_query_stats_error_queries{namespace=\"$env\", app=\"$ksqldb_cluster\"})"
    }
   ]
  },
  {
   "title": "Cluster Liveness",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "ksql_ksql_engine_query_stats_liveness_indicator{namespace=\"$env\",app=\"$ksqldb_cluster\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Messages consumed/sec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "ksql_ksql_engine_query_stats_messages_consumed_per_sec{namespace=\"$env\",app=\"$ksqldb_cluster\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Messages produced/sec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "ksql_ksql_engine_query_stats_messages_produced_per_sec{namespace=\"$env\",app=\"$ksqldb_cluster\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "Rate of CPU seconds used by the Java process.\n            100% usage represents one core. \n            If there are multiple cores, the total capacity should be 100% * number_cores.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{namespace=\"$env\",app=\"$ksqldb_cluster\",pod=~\"$ksqldb_server\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Sum of JVM memory used, without including areas (e.g. heap size).",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{namespace=\"$env\",app=\"$ksqldb_cluster\",pod=~\"$ksqldb_server\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC collection",
   "type": "timeseries",
   "description": "Sum of seconds used by Garbage Collection.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(gc)(irate(jvm_gc_collection_seconds_sum{namespace=\"$env\",app=\"$ksqldb_cluster\",pod=~\"$ksqldb_server\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Queries Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Poll Latency (Avg.)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_poll_latency_avg{namespace=\"$env\",app=\"$ksqldb_cluster\",pod=~\"$ksqldb_server\",thread_id=~\".+$ksqldb_cluster_id.+\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    },
    {
     "title": "Poll Latency (Max.)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_poll_latency_max{namespace=\"$env\",app=\"$ksqldb_cluster\",pod=~\"$ksqldb_server\",thread_id=~\".+$ksqldb_cluster_id.+\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    },
    {
     "title": "Process Latency (Avg.)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_process_latency_avg{namespace=\"$env\",app=\"$ksqldb_cluster\",pod=~\"$ksqldb_server\",thread_id=~\".+$ksqldb_cluster_id.+\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    },
    {
     "title": "Process Latency (Max.)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_process_latency_max{namespace=\"$env\",app=\"$ksqldb_cluster\",pod=~\"$ksqldb_server\",thread_id=~\".+$ksqldb_cluster_id.+\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    },
    {
     "title": "Commit Latency (Avg.)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_commit_latency_avg{namespace=\"$env\",app=\"$ksqldb_cluster\",pod=~\"$ksqldb_server\",thread_id=~\".+$ksqldb_cluster_id.+\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    },
    {
     "title": "Commit Latency (Max.)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_commit_latency_max{namespace=\"$env\",app=\"$ksqldb_cluster\",pod=~\"$ksqldb_server\",thread_id=~\".+$ksqldb_cluster_id.+\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    },
    {
     "title": "Punctuate Latency (Avg.)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_punctuate_latency_avg{namespace=\"$env\",app=\"$ksqldb_cluster\",pod=~\"$ksqldb_server\",thread_id=~\".+$ksqldb_cluster_id.+\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    },
    {
     "title": "Punctuate Latency (Max.)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_punctuate_latency_max{namespace=\"$env\",app=\"$ksqldb_cluster\",pod=~\"$ksqldb_server\",thread_id=~\".+$ksqldb_cluster_id.+\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "State Stores",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Put Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_put_rate{namespace=\"$env\",app=\"$ksqldb_cluster\",pod=~\"$ksqldb_server\",thread_id=~\".+$ksqldb_cluster_id.+\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    },
    {
     "title": "Put Latency (Avg.)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_put_latency_avg{namespace=\"$env\",app=\"$ksqldb_cluster\",pod=~\"$ksqldb_server\",thread_id=~\".+$ksqldb_cluster_id.+\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    },
    {
     "title": "Put Latency (Max.)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_put_latency_max{namespace=\"$env\",app=\"$ksqldb_cluster\",pod=~\"$ksqldb_server\",thread_id=~\".+$ksqldb_cluster_id.+\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    },
    {
     "title": "Put if absent Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_put_if_absent_rate{namespace=\"$env\",app=\"$ksqldb_cluster\",pod=~\"$ksqldb_server\",thread_id=~\".+$ksqldb_cluster_id.+\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    },
    {
     "title": "Put if absent Latency (Avg.)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_put_if_absent_latency_avg{namespace=\"$env\",app=\"$ksqldb_cluster\",pod=~\"$ksqldb_server\",thread_id=~\".+$ksqldb_cluster_id.+\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    },
    {
     "title": "Put if absent Latency (Max.)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_put_if_absent_latency_max{namespace=\"$env\",app=\"$ksqldb_cluster\",pod=~\"$ksqldb_server\",thread_id=~\".+$ksqldb_cluster_id.+\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    },
    {
     "title": "Fetch Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_fetch_rate{namespace=\"$env\",app=\"$ksqldb_cluster\",pod=~\"$ksqldb_server\",thread_id=~\".+$ksqldb_cluster_id.+\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    },
    {
     "title": "Fetch Latency (Avg.)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_fetch_latency_avg{namespace=\"$env\",app=\"$ksqldb_cluster\",pod=~\"$ksqldb_server\",thread_id=~\".+$ksqldb_cluster_id.+\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    },
    {
     "title": "Fetch Latency (Max.)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_fetch_latency_max{namespace=\"$env\",app=\"$ksqldb_cluster\",pod=~\"$ksqldb_server\",thread_id=~\".+$ksqldb_cluster_id.+\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    },
    {
     "title": "Delete Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_delete_rate{namespace=\"$env\",app=\"$ksqldb_cluster\",pod=~\"$ksqldb_server\",thread_id=~\".+$ksqldb_cluster_id.+\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    },
    {
     "title": "Delete Latency (Avg.)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_delete_latency_avg{namespace=\"$env\",app=\"$ksqldb_cluster\",pod=~\"$ksqldb_server\",thread_id=~\".+$ksqldb_cluster_id.+\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    },
    {
     "title": "Delete Latency (Max.)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_delete_latency_max{namespace=\"$env\",app=\"$ksqldb_cluster\",pod=~\"$ksqldb_server\",thread_id=~\".+$ksqldb_cluster_id.+\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    },
    {
     "title": "Restore Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_restore_rate{namespace=\"$env\",app=\"$ksqldb_cluster\",pod=~\"$ksqldb_server\",thread_id=~\".+$ksqldb_cluster_id.+\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    },
    {
     "title": "Restore Latency (Avg.)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_restore_latency_avg{namespace=\"$env\",app=\"$ksqldb_cluster\",pod=~\"$ksqldb_server\",thread_id=~\".+$ksqldb_cluster_id.+\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    },
    {
     "title": "Restore Latency (Max.)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_restore_latency_max{namespace=\"$env\",app=\"$ksqldb_cluster\",pod=~\"$ksqldb_server\",thread_id=~\".+$ksqldb_cluster_id.+\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    }
   ]
  }
 ]
}