services:
  prometheus:
    image: prom/prometheus:v2.29.2
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - $MONITORING_STACK/assets/prometheus/prometheus-config/:/etc/prometheus

  grafana:
    image: grafana/grafana:8.5.27
    container_name: grafana
    environment:
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_ADMIN_PASSWORD=password"
      - "GF_USERS_ALLOW_SIGN_UP=false"
    ports:
      - 3000:3000
    volumes:
      - $MONITORING_STACK/assets/grafana/provisioning/:/etc/grafana/provisioning
  
  confluent_cost_exporter:
    image: docker.io/mcolomerc/confluent-costs-exporter:latest
    platform: linux/amd64
    container_name: confluent_cost_exporter
    environment:
    - CONFLUENT_CLOUD_API_KEY=$CONFLUENT_CLOUD_API_KEY
    - CONFLUENT_CLOUD_API_SECRET=$CONFLUENT_CLOUD_API_SECRET
    - CACHE_EXPIRATION=240m
    - PORT=7979 
    ports:
      - 7979:7979
