services:
  zookeeper:
    ports:
      - "8777:8777"
    volumes:
      - $MONITORING_STACK/../shared-assets/jolokia-agent/:/usr/share/jolokia-agent
    environment:
      EXTRA_ARGS: -javaagent:/usr/share/jolokia-agent/jolokia-agent-jvm-2.0.0-javaagent.jar=port=8777,host=0.0.0.0

  kafka1:
    ports:
      - "8778:8778"
    volumes:
      - $MONITORING_STACK/../shared-assets/jolokia-agent/:/usr/share/jolokia-agent
    environment:
      EXTRA_ARGS: -javaagent:/usr/share/jolokia-agent/jolokia-agent-jvm-2.0.0-javaagent.jar=port=8778,host=0.0.0.0

  kafka2:
    ports:
      - "8779:8779"
    volumes:
      - $MONITORING_STACK/../shared-assets/jolokia-agent/:/usr/share/jolokia-agent
    environment:
      EXTRA_ARGS: -javaagent:/usr/share/jolokia-agent/jolokia-agent-jvm-2.0.0-javaagent.jar=port=8779,host=0.0.0.0

  streams-demo:
    ports:
      - "8780:8780"
    volumes:
      - $MONITORING_STACK/../shared-assets/jolokia-agent/:/usr/share/jolokia-agent
    environment:
      JAVA_OPTS: -javaagent:/usr/share/jolokia-agent/jolokia-agent-jvm-2.0.0-javaagent.jar=port=8780,host=0.0.0.0

  connect:
    ports:
      - "8781:8781"
    volumes:
      - $MONITORING_STACK/../shared-assets/jolokia-agent/:/usr/share/jolokia-agent
    environment:
      EXTRA_ARGS: -javaagent:/usr/share/jolokia-agent/jolokia-agent-jvm-2.0.0-javaagent.jar=port=8781,host=0.0.0.0

  schemaregistry:
    ports:
      - "8782:8782"
    volumes:
      - $MONITORING_STACK/../shared-assets/jolokia-agent/:/usr/share/jolokia-agent
    environment:
      EXTRA_ARGS: -javaagent:/usr/share/jolokia-agent/jolokia-agent-jvm-2.0.0-javaagent.jar=port=8782,host=0.0.0.0

  ksqldb-server:
    ports:
      - "8783:8783"
    volumes:
      - $MONITORING_STACK/../shared-assets/jolokia-agent/:/usr/share/jolokia-agent
    environment:
      KSQL_OPTS: -javaagent:/usr/share/jolokia-agent/jolokia-agent-jvm-2.0.0-javaagent.jar=port=8783,host=0.0.0.0

  restproxy:
    ports:
      - "8784:8784"
    volumes:
      - $MONITORING_STACK/../shared-assets/jolokia-agent/:/usr/share/jolokia-agent
    environment:
      KAFKAREST_OPTS: -javaagent:/usr/share/jolokia-agent/jolokia-agent-jvm-2.0.0-javaagent.jar=port=8784,host=0.0.0.0

  kafka-lag-exporter:
    image: seglo/kafka-lag-exporter:0.7.1
    container_name: kafka-lag-exporter
    hostname: kafka-lag-exporter
    restart: always
    volumes:
      - $MONITORING_STACK/../shared-assets/kafka-lag-exporter:/opt/docker/conf
      - $MONITORING_STACK/assets/security:/etc/kafka/secrets

  telegraf:
    image: telegraf:1.29.2
    container_name: telegraf
    restart: always
    ports:
      - '57100:57100'
      - '57500:57500'
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    volumes:
      - $MONITORING_STACK/assets/telegraf/:/etc/telegraf
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro

  influxdb:
    image: influxdb:2.7.5
    container_name: influxdb
    restart: always
    ports:
      - '9086:8086'
    volumes:
      - $MONITORING_STACK/assets/influxdb/template:/tmp/template