{
 "title": "Kafka Connect cluster - v2",
 "description": "Overview of the Kafka Connect cluster",
 "tags": [
  "confluent",
  "kafka-connect"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ns", "label": "Namespace", "query": "label_values(namespace)" },
   {
    "name": "connect_app",
    "label": "Connect group",
    "query": "label_values(kafka_connect_connect_worker_metrics_connector_total_task_count{namespace=\"$ns\"}, app)"
   },
   {
    "name": "connect_worker",
    "label": "Connect worker",
    "query": "label_values(kafka_connect_connect_worker_metrics_connector_total_task_count{namespace=\"$ns\",app=\"$connect_app\"}, pod)"
   },
   {
    "name": "connector",
    "label": "Connector",
    "query": "label_values(kafka_connect_connector_task_metrics_pause_ratio{namespace=\"$ns\",app=\"$connector_app\"}, connector)"
   }
  ]
 },
 "panels": [
  { "title": "Health-check", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connect: Online Workers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kafka_connect_app_info{namespace=\"$ns\",app=\"$connect_app\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Connect: Sum of Total Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_total_task_count{namespace=\"$ns\",app=\"$connect_app\"})"
    }
   ]
  },
  {
   "title": "Connect: Sum of Running Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_running_task_count{namespace=\"$ns\",app=\"$connect_app\"})"
    }
   ]
  },
  {
   "title": "Connect: Sum of Paused Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_paused_task_count{namespace=\"$ns\",app=\"$connect_app\"})"
    }
   ]
  },
  {
   "title": "Connect: Sum of Failed Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_failed_task_count{namespace=\"$ns\",app=\"$connect_app\"})"
    }
   ]
  },
  {
   "title": "Connect: Time since last rebalance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "clockms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_rebalance_metrics_time_since_last_rebalance_ms{namespace=\"$ns\",app=~\"$connect_app\"} >= 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{namespace=\"$ns\",app=\"$connect_app\",type=\"connect\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{namespace=\"$ns\",app=\"$connect_app\",type=\"connect\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC collection",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(gc)(irate(jvm_gc_collection_seconds_sum{namespace=\"$ns\",app=\"$connect_app\",type=\"connect\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}