all:
	generate-dashboard -o confluent-platform.json confluent-platform.py
	generate-dashboard -o zookeeper-cluster.json zookeeper-cluster.py
	generate-dashboard -o kafka-cluster.json kafka-cluster.py
	generate-dashboard -o kafka-topics.json kafka-topics.py
