all:
	generate-dashboard -o confluent-platform.json confluent-platform.py
	generate-dashboard -o zookeeper-cluster.json zookeeper-cluster.py
	generate-dashboard -o kafka-cluster.json kafka-cluster.py
	generate-dashboard -o kafka-topics.json kafka-topics.py
	generate-dashboard -o schema-registry-cluster.json schema-registry-cluster.py
	generate-dashboard -o kafka-connect-cluster.json kafka-connect-cluster.py
	generate-dashboard -o ksqldb-cluster.json ksqldb-cluster.py
