{
 "title": "Zookeeper cluster - v2",
 "description": "Overview of the Zookeeper cluster",
 "tags": [
  "confluent",
  "kafka",
  "zookeeper"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ns", "label": "Namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  { "title": "Health-check", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ZK: Quorum Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(zookeeper_status_quorumsize{namespace=\"$ns\"})"
    }
   ]
  },
  {
   "title": "ZK: Avg. number of ZNodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(zookeeper_inmemorydatatree_nodecount{namespace=\"$ns\"})"
    }
   ]
  },
  {
   "title": "ZK: Sum of number of Alive Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(zookeeper_numaliveconnections{namespace=\"$ns\"})"
    }
   ]
  },
  {
   "title": "ZK: Sum of watchers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(zookeeper_inmemorydatatree_watchcount{namespace=\"$ns\"})"
    }
   ]
  },
  {
   "title": "ZK: Outstanding Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "zookeeper_outstandingrequests{namespace=\"$ns\"}",
     "legendFormat": "{{pod}} ({{server_id}}:{{member_type}})"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "ZK: CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{namespace=\"$ns\",type=\"zookeeper\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ZK: Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{namespace=\"$ns\",type=\"zookeeper\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ZK: GC collection",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(gc)(irate(jvm_gc_collection_seconds_sum{namespace=\"$ns\",type=\"zookeeper\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "ZK: Request Latency (Minimum)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "zookeeper_minrequestlatency{namespace=\"$ns\"} * zookeeper_ticktime",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ZK: Request Latency (Average)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "zookeeper_avgrequestlatency{namespace=\"$ns\"} * zookeeper_ticktime",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ZK: Request Latency (Maximum)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "zookeeper_maxrequestlatency{namespace=\"$ns\"} * zookeeper_ticktime",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}