global:
  # How frequently to scrape targets by default.
  # Default 15s
  scrape_interval: 60s
  # How frequently to evaluate rules.
  # Default 15s
  evaluation_interval: 15s
  # How long until a scrape request times out.
  # Default to 10s.
  # Required because cp-demo is using cpu throttling, so let's leave enough time to fetch the metrics in particular for the first time as it needs to compile all rexps
  scrape_timeout: 30s

rule_files:
  - "alert.rules"

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]


  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: hostname
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'


  - job_name: "zookeeper"
    static_configs:
      - targets:
          - "zookeeper:1234"
        labels:
          env: "dev"
    relabel_configs:
      - source_labels: [__address__]
        target_label: hostname
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'


  - job_name: "kafka-broker"
    static_configs:
      - targets:
          - "kafka1:1234"
          - "kafka2:1234"
        labels:
          env: "dev"
    relabel_configs:
      - source_labels: [__address__]
        target_label: hostname
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'


  - job_name: "schema-registry"
    static_configs:
      - targets:
          - "schemaregistry:1234"
        labels:
          env: "dev"
    relabel_configs:
      - source_labels: [__address__]
        target_label: hostname
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'


  - job_name: "kafka-connect"
    static_configs:
      - targets:
          - "connect:1234"
        labels:
          env: "dev"
          kafka_connect_cluster_id: "cluster1"
    relabel_configs:
      - source_labels: [__address__]
        target_label: hostname
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'

  - job_name: "flink"
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      # Keep only TaskManager pods with matching name pattern
      - source_labels: [__meta_kubernetes_pod_name]
        regex: .+(?:-taskmanager-[0-9]+-[0-9]+|-.*)
        action: keep
  
      # Use pod IP and append port 9249
      - source_labels: [__meta_kubernetes_pod_ip]
        target_label: __address__
        replacement: ${1}:9249
  
      # Optional: Add pod name as a label for PromQL queries
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
  
      # Optional: Add namespace
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace

      # Assign "taskManager" based on name match
      - source_labels: [__meta_kubernetes_pod_name]
        regex: .+-taskmanager-[0-9]+-[0-9]+
        target_label: role_type
        replacement: taskManager
        action: replace

      # Assign "jobManager" only if "role_type" is still missing
      - target_label: role_type
        replacement: jobManager
        action: replace
        regex: ""           # only replace if missing
        source_labels: [role_type]
      
      # add an "env" label
      - target_label: env
        replacement: dev
        action: replace

      # add "flink_cluster_id"
      - target_label: flink_cluster_id
        replacement: basic-example-cluster
        action: replace

      - source_labels: [__address__]
        target_label: hostname
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'

  - job_name: "ksqldb"
    static_configs:
      - targets:
          - "ksqldb-server:1234"
        labels:
          env: "dev"
    relabel_configs:
      - source_labels: [__address__]
        target_label: hostname
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'


  - job_name: "streams-demo"
    static_configs:
      - targets:
          - "streams-demo:1234"
        labels:
          env: "dev"
    relabel_configs:
      - source_labels: [__address__]
        target_label: hostname
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'

  - job_name: "librdkafka-demo"
    static_configs:
      - targets:
          - "librdkafka-demo:7071"
        labels:
          env: "dev"
    relabel_configs:
      - source_labels: [__address__]
        target_label: hostname
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'

  - job_name: "rest-proxy"
    static_configs:
      - targets:
          - "restproxy:1234"
        labels:
          env: "dev"
    relabel_configs:
      - source_labels: [__address__]
        target_label: hostname
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'

  # No producer for the moment in cp-demo
  # - job_name: 'kafka-producer'
  #   static_configs:
  #     - targets:
  #         - 'kafka1:1235'
  #       labels:
  #         env: 'dev'
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: hostname
  #       regex: '([^:]+)(:[0-9]+)?'
  #       replacement: '${1}'

  # No consumer for the moment in cp-demo
  # - job_name: 'kafka-consumer'
  #   static_configs:
  #     - targets:
  #         - "kafka1:1236"
  #       labels:
  #         env: 'dev'
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: hostname
  #       regex: '([^:]+)(:[0-9]+)?'
  #       replacement: '${1}'

  - job_name: "kafka-lag-exporter"
    static_configs:
      - targets:
          - "kafka-lag-exporter:9999"
        labels:
          env: "dev"
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'    