{
 "title": "Confluent Platform overview - v2",
 "description": "Overview of the main health-check metrics from Confluent Platform components.",
 "tags": [
  "confluent",
  "kafka",
  "zookeeper",
  "kafka-connect",
  "schema-registry",
  "ksqldb"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": "label_values(namespace)" },
   {
    "name": "connect_cluster",
    "label": "Kafka Connect cluster",
    "query": "label_values(kafka_connect_connect_worker_metrics_connector_count{namespace=\"$env\"}, app)"
   },
   {
    "name": "ksqldb_cluster",
    "label": "ksqlDB cluster",
    "query": "label_values(ksql_ksql_engine_query_stats_liveness_indicator{namespace=\"$env\"}, app)"
   }
  ]
 },
 "panels": [
  { "title": "Zookeeper cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ZK: Quorum Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(zookeeper_status_quorumsize{namespace=\"$env\"})"
    }
   ]
  },
  {
   "title": "ZK: Avg. number of ZNodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(zookeeper_inmemorydatatree_nodecount{namespace=\"$env\"})"
    }
   ]
  },
  {
   "title": "ZK: Sum of number of Alive Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(zookeeper_numaliveconnections{namespace=\"$env\"})"
    }
   ]
  },
  {
   "title": "ZK: Sum of watchers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(zookeeper_inmemorydatatree_watchcount{namespace=\"$env\"})"
    }
   ]
  },
  {
   "title": "ZK: Outstanding Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "zookeeper_outstandingrequests{namespace=\"$env\"}",
     "legendFormat": "{{pod}} ({{server_id}}:{{member_type}})"
    }
   ]
  },
  { "title": "Kafka cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Kafka: Online Brokers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount{namespace=\"$env\"})"
    }
   ]
  },
  {
   "title": "Kafka: Active Controller",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount{namespace=\"$env\"} > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Kafka: Sum of Partitioenv",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount{namespace=\"$env\"})"
    }
   ]
  },
  {
   "title": "Kafka: Sum of Partitions Under-Replicated (URP)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions{namespace=\"$env\"})"
    }
   ]
  },
  {
   "title": "Kafka: Sum of Partitioenv Under-MinISR",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underminisr{namespace=\"$env\"})"
    }
   ]
  },
  {
   "title": "Kafka: Sum of Partitions Offline",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{namespace=\"$env\"})"
    }
   ]
  },
  { "title": "Schema Registry cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "SR: Online instances",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kafka_schema_registry_registered_count{namespace=\"$env\"})"
    }
   ]
  },
  {
   "title": "SR: Sum of Registered Schemas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(kafka_schema_registry_registered_count{namespace=\"$env\"})"
    }
   ]
  },
  {
   "title": "SR: Sum of Created Schemas by Type",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(kafka_schema_registry_schemas_created{namespace=\"$env\"}) by (schema_type)",
     "legendFormat": "{{schema_type}}"
    }
   ]
  },
  {
   "title": "SR: Sum of Deleted Schemas by Type",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_schema_registry_schemas_deleted{namespace=\"$env\"}) by (schema_type)",
     "legendFormat": "{{schema_type}}"
    }
   ]
  },
  {
   "title": "Kafka Connect cluster: $connect_cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "repeat": "connect_cluster",
   "collapsed": true,
   "panels": [
    {
     "title": "Connect: Online Workers",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(kafka_connect_connect_worker_metrics_connector_count{namespace=\"$env\",app=~\"$connect_cluster\"})"
      }
     ]
    },
    {
     "title": "Connect: Sum of Total Tasks",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kafka_connect_connect_worker_metrics_connector_total_task_count{namespace=\"$env\",app=~\"$connect_cluster\"})"
      }
     ]
    },
    {
     "title": "Connect: Sum of Running Tasks",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kafka_connect_connect_worker_metrics_connector_running_task_count{namespace=\"$env\",app=~\"$connect_cluster\"})"
      }
     ]
    },
    {
     "title": "Connect: Sum of Paused Tasks",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kafka_connect_connect_worker_metrics_connector_paused_task_count{namespace=\"$env\",app=~\"$connect_cluster\"})"
      }
     ]
    },
    {
     "title": "Connect: Sum of Failed Tasks",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kafka_connect_connect_worker_metrics_connector_failed_task_count{namespace=\"$env\",app=~\"$connect_cluster\"})"
      }
     ]
    },
    {
     "title": "Connect: Time since last rebalance",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "clockms" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "kafka_connect_connect_worker_rebalance_metrics_time_since_last_rebalance_ms{namespace=\"$env\",app=~\"$connect_cluster\"} >= 0",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ksqlDB cluster: $ksqldb_cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "ksqldb_cluster",
   "collapsed": true,
   "panels": [
    {
     "title": "ksqlDB: Online Servers",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(ksql_ksql_engine_query_stats_num_active_queries{namespace=\"$env\", app=\"$ksqldb_cluster\"})"
      }
     ]
    },
    {
     "title": "ksqlDB: Sum of Active Queries",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(ksql_ksql_engine_query_stats_num_active_queries{namespace=\"$env\", app=\"$ksqldb_cluster\"})"
      }
     ]
    },
    {
     "title": "ksqlDB: Sum of Running Queries",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(ksql_ksql_engine_query_stats_running_queries{namespace=\"$env\", app=\"$ksqldb_cluster\"})"
      }
     ]
    },
    {
     "title": "ksqlDB: Sum of Rebalancing Queries",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(ksql_ksql_engine_query_stats_rebalancing_queries{namespace=\"$env\", app=\"$ksqldb_cluster\"})"
      }
     ]
    },
    {
     "title": "Connect: Sum of Failed Queries",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "avg(ksql_ksql_engine_query_stats_error_queries{namespace=\"$env\", app=\"$ksqldb_cluster\"})"
      }
     ]
    }
   ]
  }
 ]
}