{
 "title": "Kafka cluster - v2",
 "description": "Overview of the Kafka cluster",
 "tags": [
  "confluent",
  "kafka"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": "label_values(namespace)" },
   {
    "name": "broker",
    "label": "Broker",
    "query": "label_values(kafka_server_replicamanager_leadercount{namespace=\"$env\"}, pod)"
   },
   {
    "name": "quantile",
    "label": "Quantile",
    "query": "label_values(kafka_network_requestmetrics_requestqueuetimems{namespace=\"$env\"}, quantile)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kafka: Online Brokers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount{namespace=\"$env\"})"
    }
   ]
  },
  {
   "title": "Kafka: Active Controller",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount{namespace=\"$env\"} > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Kafka: Sum of Replica Imbalance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_preferredreplicaimbalancecount{namespace=\"$env\"})"
    }
   ]
  },
  {
   "title": "Kafka: Sum of Topics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_globaltopiccount{namespace=\"$env\"})"
    }
   ]
  },
  {
   "title": "Kafka: Rate of Requests/Sec",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_requestspersec{namespace=\"$env\",pod=~\"$broker\"}[5m]))"
    }
   ]
  },
  {
   "title": "Kafka: Logs Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_log_log_size{namespace=\"$env\",pod=~\"$broker\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Kafka: Sum of Partitions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount{namespace=\"$env\",pod=~\"$broker\"})"
    }
   ]
  },
  {
   "title": "Kafka: Sum of Partitions Under-Replicated (URP)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions{namespace=\"$env\",pod=~\"$broker\"})"
    }
   ]
  },
  {
   "title": "Kafka: Sum of Partitions Under-MinISR",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underminisr{namespace=\"$env\",pod=~\"$broker\"})"
    }
   ]
  },
  {
   "title": "Kafka: Sum of Partitions Offline",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{namespace=\"$env\",pod=~\"$broker\"})"
    }
   ]
  },
  {
   "title": "Kafka: Bytes In/Sec",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesinpersec{namespace=\"$env\",pod=~\"$broker\"}[5m]))"
    }
   ]
  },
  {
   "title": "Kafka: Bytes Out/Sec",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesoutpersec{namespace=\"$env\",pod=~\"$broker\"}[5m]))"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{namespace=\"$env\",pod=~\"$broker\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{namespace=\"$env\",pod=~\"$broker\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC collection",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(gc)(irate(jvm_gc_collection_seconds_sum{namespace=\"$env\",pod=~\"$broker\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "description": "Bytes in/out per second",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages In/Sec",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum without(topic) (rate(kafka_server_brokertopicmetrics_messagesinpersec{namespace=\"$env\",pod=~\"$broker\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Bytes In/Sec",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum without(topic) (rate(kafka_server_brokertopicmetrics_bytesinpersec{namespace=\"$env\",pod=~\"$broker\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Bytes Out/Sec",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum without(topic) (rate(kafka_server_brokertopicmetrics_bytesoutpersec{namespace=\"$env\",pod=~\"$broker\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Thread Utilization",
   "type": "row",
   "description": "Internal thread pools usage",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network processor usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1-kafka_network_socketserver_networkprocessoravgidlepercent{namespace=\"$env\",pod=~\"$broker\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Request processor (IO) usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1-kafka_server_kafkarequesthandlerpool_requesthandleravgidlepercent_total{namespace=\"$env\",pod=~\"$broker\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Request rates",
   "type": "row",
   "description": "Sum of req/sec rates",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests rates",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum without(pod,instance,statefulset_kubernetes_io_pod_name)(rate(kafka_network_requestmetrics_requestspersec{namespace=\"$env\",pod=~\"$broker\"}[5m]))",
       "legendFormat": "{{request}}(v{{version}})"
      }
     ]
    },
    {
     "title": "Error rates",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum without(pod,instance,statefulset_kubernetes_io_pod_name)(rate(kafka_network_requestmetrics_errorspersec{namespace=\"$env\",pod=~\"$broker\",error!=\"NONE\"}[5m]))",
       "legendFormat": "{{error}}@{{request}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sum of Connections alive per Broker",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "sum(kafka_server_socketservermetrics_connection_count{namespace=\"$env\",pod=~\"$broker\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Sum of Connections creation rate per Broker",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 6 },
     "targets": [
      {
       "expr": "sum(kafka_server_socketservermetrics_connection_creation_rate{namespace=\"$env\",pod=~\"$broker\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Sum of Connections close rate per Broker",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 6 },
     "targets": [
      {
       "expr": "sum(kafka_server_socketservermetrics_connection_close_rate{namespace=\"$env\",pod=~\"$broker\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Sum of Connections alive per Listener",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum(kafka_server_socketservermetrics_connection_count{namespace=\"$env\",pod=~\"$broker\"}) by (listener)",
       "legendFormat": "{{listener}}"
      }
     ]
    },
    {
     "title": "Sum of Connections creation rate per Listener",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 7 },
     "targets": [
      {
       "expr": "sum(kafka_server_socketservermetrics_connection_creation_rate{namespace=\"$env\",pod=~\"$broker\"}) by (listener)",
       "legendFormat": "{{listener}}"
      }
     ]
    },
    {
     "title": "Sum of Connections close rate per Listener",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 7 },
     "targets": [
      {
       "expr": "sum(kafka_server_socketservermetrics_connection_close_rate{namespace=\"$env\",pod=~\"$broker\"}) by (listener)",
       "legendFormat": "{{listener}}"
      }
     ]
    }
   ]
  },
  {
   "title": "In-Sync Replicas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate of ISR Shrinks/sec",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "rate(kafka_server_replicamanager_isrshrinkspersec{namespace=\"$env\",pod=~\"$broker\"}[5m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Rate of ISR Expands/sec",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 8 },
     "targets": [
      {
       "expr": "rate(kafka_server_replicamanager_isrexpandspersec{namespace=\"$env\",pod=~\"$broker\"}[5m])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Request latency: Producer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Produce: Request Queue Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_requestqueuetimems{namespace=\"$env\",pod=~\"$broker\",quantile=~\"$quantile\",request=\"Produce\"}",
       "legendFormat": "{{pod}} ({{quantile}}th)"
      }
     ]
    },
    {
     "title": "Produce: Local Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_localtimems{namespace=\"$env\",pod=~\"$broker\",quantile=~\"$quantile\",request=\"Produce\"}",
       "legendFormat": "{{pod}} ({{quantile}}th)"
      }
     ]
    },
    {
     "title": "Produce: Remote Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_remotetimems{namespace=\"$env\",pod=~\"$broker\",quantile=~\"$quantile\",request=\"Produce\"}",
       "legendFormat": "{{pod}} ({{quantile}}th)"
      }
     ]
    },
    {
     "title": "Produce: Response Queue Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_responsequeuetimems{namespace=\"$env\",pod=~\"$broker\",quantile=~\"$quantile\",request=\"Produce\"}",
       "legendFormat": "{{pod}} ({{quantile}}th)"
      }
     ]
    },
    {
     "title": "Produce: Response Send Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_responsesendtimems{namespace=\"$env\",pod=~\"$broker\",quantile=~\"$quantile\",request=\"Produce\"}",
       "legendFormat": "{{pod}} ({{quantile}}th)"
      }
     ]
    }
   ]
  },
  {
   "title": "Request latency: Consumer Fetch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fetch: Request Queue Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_requestqueuetimems{namespace=\"$env\",pod=~\"$broker\",quantile=~\"$quantile\",request=\"Fetch\"}",
       "legendFormat": "{{pod}} ({{quantile}}th)"
      }
     ]
    },
    {
     "title": "Fetch: Local Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_localtimems{namespace=\"$env\",pod=~\"$broker\",quantile=~\"$quantile\",request=\"Fetch\"}",
       "legendFormat": "{{pod}} ({{quantile}}th)"
      }
     ]
    },
    {
     "title": "Fetch: Remote Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_remotetimems{namespace=\"$env\",pod=~\"$broker\",quantile=~\"$quantile\",request=\"Fetch\"}",
       "legendFormat": "{{pod}} ({{quantile}}th)"
      }
     ]
    },
    {
     "title": "Fetch: Response Queue Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_responsequeuetimems{namespace=\"$env\",pod=~\"$broker\",quantile=~\"$quantile\",request=\"Fetch\"}",
       "legendFormat": "{{pod}} ({{quantile}}th)"
      }
     ]
    },
    {
     "title": "Fetch: Response Send Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_responsesendtimems{namespace=\"$env\",pod=~\"$broker\",quantile=~\"$quantile\",request=\"Fetch\"}",
       "legendFormat": "{{pod}} ({{quantile}}th)"
      }
     ]
    }
   ]
  },
  {
   "title": "Request latency: Replica Fetch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fetch: Request Queue Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_requestqueuetimems{namespace=\"$env\",pod=~\"$broker\",quantile=~\"$quantile\",request=\"FetchFollower\"}",
       "legendFormat": "{{pod}} ({{quantile}}th)"
      }
     ]
    },
    {
     "title": "Fetch: Local Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_localtimems{namespace=\"$env\",pod=~\"$broker\",quantile=~\"$quantile\",request=\"FetchFollower\"}",
       "legendFormat": "{{pod}} ({{quantile}}th)"
      }
     ]
    },
    {
     "title": "Fetch: Remote Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_remotetimems{namespace=\"$env\",pod=~\"$broker\",quantile=~\"$quantile\",request=\"FetchFollower\"}",
       "legendFormat": "{{pod}} ({{quantile}}th)"
      }
     ]
    },
    {
     "title": "Fetch: Response Queue Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_responsequeuetimems{namespace=\"$env\",pod=~\"$broker\",quantile=~\"$quantile\",request=\"FetchFollower\"}",
       "legendFormat": "{{pod}} ({{quantile}}th)"
      }
     ]
    },
    {
     "title": "Fetch: Response Send Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_responsesendtimems{namespace=\"$env\",pod=~\"$broker\",quantile=~\"$quantile\",request=\"FetchFollower\"}",
       "legendFormat": "{{pod}} ({{quantile}}th)"
      }
     ]
    }
   ]
  },
  {
   "title": "Group Coordinator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Groups per Broker",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "kafka_coordinator_group_groupmetadatamanager_numgroups{namespace=\"$env\",pod=~\"$broker\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of Groups per Broker",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 15 },
     "targets": [
      {
       "expr": "sum(kafka_coordinator_group_groupmetadatamanager_numgroupsstable{namespace=\"$env\",pod=~\"$broker\"})",
       "legendFormat": "stable"
      },
      {
       "expr": "sum(kafka_coordinator_group_groupmetadatamanager_numgroupspreparingrebalance{namespace=\"$env\",pod=~\"$broker\"})",
       "legendFormat": "preparing_rebalance"
      },
      {
       "expr": "sum(kafka_coordinator_group_groupmetadatamanager_numgroupsdead{namespace=\"$env\",pod=~\"$broker\"})",
       "legendFormat": "dead"
      },
      {
       "expr": "sum(kafka_coordinator_group_groupmetadatamanager_numgroupscompletingrebalance{namespace=\"$env\",pod=~\"$broker\"})",
       "legendFormat": "completing_rebalance"
      },
      {
       "expr": "sum(kafka_coordinator_group_groupmetadatamanager_numgroupsempty{namespace=\"$env\",pod=~\"$broker\"})",
       "legendFormat": "empty"
      }
     ]
    }
   ]
  },
  {
   "title": "Message Conversion",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sum of Produce conversion rate per sec",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "opsps" } },
     "targets": [
      {
       "expr": "sum(kafka_server_brokertopicmetrics_producemessageconversionspersec{namespace=\"$env\",pod=~\"$broker\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Sum of Fetch conversion rate per sec",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "opsps" } },
     "targets": [
      {
       "expr": "sum(kafka_server_brokertopicmetrics_fetchmessageconversionspersec{namespace=\"$env\",pod=~\"$broker\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Sum of Connections per version",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 16 },
     "targets": [
      {
       "expr": "sum(kafka_server_socketservermetrics_connections{namespace=\"$env\",pod=~\"$broker\"}) by (client_software_name,client_software_version)",
       "legendFormat": "{{client_software_name}} (v{{client_software_version}})"
      }
     ]
    }
   ]
  }
 ]
}