{
 "title": "Kafka Producer - v2",
 "description": "Overview of the Kafka producers",
 "tags": [
  "confluent",
  "kafka-client",
  "kafka-producer"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": "label_values(namespace)" },
   {
    "name": "server",
    "label": "Server",
    "query": "label_values(kafka_producer_producer_metrics_record_retry_rate{namespace=\"$env\", client_type=\"producer\"},pod)"
   },
   {
    "name": "client_id",
    "label": "Client ID",
    "query": "label_values(kafka_producer_producer_metrics_record_retry_rate{namespace=\"$env\", client_type=\"producer\"},client_id)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Record Send Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(10, kafka_producer_producer_metrics_record_send_rate{namespace=\"$env\", client_type=\"producer\", client_id=~\"$client_id\", pod=~\"$server\"} > 0)",
     "legendFormat": "{{client_id}}@{{pod}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(10, kafka_producer_producer_metrics_record_error_rate{namespace=\"$env\", client_type=\"producer\", client_id=~\"$client_id\", pod=~\"$server\"} > 0)",
     "legendFormat": "{{client_id}}@{{pod}}"
    }
   ]
  },
  {
   "title": "Retry Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(10, kafka_producer_producer_metrics_record_retry_rate{namespace=\"$env\", client_type=\"producer\", client_id=~\"$client_id\", pod=~\"$server\"} > 0)",
     "legendFormat": "{{client_id}}@{{pod}}"
    }
   ]
  },
  {
   "title": "Versions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kafka_producer_app_info{namespace=\"$env\", client_id=~\"$client_id\", version!=\"\", pod=~\"$server\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Incoming Byte Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk(10,kafka_producer_producer_metrics_incoming_byte_rate{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}}"
      }
     ]
    },
    {
     "title": "Outgoing Byte Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk(10,kafka_producer_producer_metrics_outgoing_byte_rate{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}}"
      }
     ]
    },
    {
     "title": "Metadata Age",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(10,kafka_producer_producer_metrics_metadata_age{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}}"
      }
     ]
    },
    {
     "title": "Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "topk(10,kafka_producer_producer_metrics_request_rate{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}}"
      }
     ]
    },
    {
     "title": "Request in-flight",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "topk(10,kafka_producer_producer_metrics_requests_in_flight{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}}"
      }
     ]
    },
    {
     "title": "Records per Request (avg.)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 2 },
     "targets": [
      {
       "expr": "topk(10,kafka_producer_producer_metrics_records_per_request_avg{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}}"
      }
     ]
    },
    {
     "title": "Record Send Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "topk(10,kafka_producer_producer_metrics_record_send_rate{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}}"
      }
     ]
    },
    {
     "title": "Record Retry Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "topk(10,kafka_producer_producer_metrics_record_retry_rate{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}}"
      }
     ]
    },
    {
     "title": "Record Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "topk(10,kafka_producer_producer_metrics_record_error_rate{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}}"
      }
     ]
    },
    {
     "title": "Record Size",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(10,kafka_producer_producer_metrics_record_size_avg{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}} (avg.)"
      },
      {
       "expr": "topk(10,kafka_producer_producer_metrics_record_size_max{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}} (max.)"
      }
     ]
    },
    {
     "title": "Record Queue Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "topk(10,kafka_producer_producer_metrics_record_queue_time_avg{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}} (avg.)"
      },
      {
       "expr": "topk(10,kafka_producer_producer_metrics_record_queue_time_max{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}} (max.)"
      }
     ]
    },
    {
     "title": "Produce Throttle Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "topk(10,kafka_producer_producer_metrics_produce_throttle_time_avg{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}} (avg.)"
      },
      {
       "expr": "topk(10,kafka_producer_producer_metrics_produce_throttle_time_max{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}} (max.)"
      }
     ]
    },
    {
     "title": "Batch Size",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(10,kafka_producer_producer_metrics_batch_size_avg{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}} (avg.)"
      },
      {
       "expr": "topk(10,kafka_producer_producer_metrics_batch_size_max{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}} (max.)"
      }
     ]
    },
    {
     "title": "Batch Split Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "topk(10,kafka_producer_producer_metrics_batch_split_rate{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}}"
      }
     ]
    },
    {
     "title": "Compression Rate (avg.)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "topk(10,kafka_producer_producer_metrics_compression_rate_avg{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connection Count",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "topk(10,kafka_producer_producer_metrics_connection_count{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}}"
      }
     ]
    },
    {
     "title": "Connection Creation Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "topk(10,kafka_producer_producer_metrics_connection_creation_rate{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}}"
      }
     ]
    },
    {
     "title": "Connection Close Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "topk(10,kafka_producer_producer_metrics_connection_close_rate{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}}"
      }
     ]
    },
    {
     "title": "IO ratio",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "topk(10,kafka_producer_producer_metrics_io_ratio{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}}"
      }
     ]
    },
    {
     "title": "IO wait ratio",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 7 },
     "targets": [
      {
       "expr": "topk(10,kafka_producer_producer_metrics_io_wait_ratio{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}}"
      }
     ]
    },
    {
     "title": "Select Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "topk(10,kafka_producer_producer_metrics_select_rate{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}}"
      }
     ]
    },
    {
     "title": "IO time avg.",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "topk(10,kafka_producer_producer_metrics_io_time_ns_avg{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}}"
      }
     ]
    },
    {
     "title": "IO wait time avg.",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "topk(10,kafka_producer_producer_metrics_io_wait_time_ns_avg{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Per Broker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Incoming Byte Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk(10,kafka_producer_producer_node_metrics_incoming_byte_rate{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}} <- {{node_id}}"
      }
     ]
    },
    {
     "title": "Outgoing Byte Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk(10,kafka_producer_producer_node_metrics_outgoing_byte_rate{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}} -> {{node_id}}"
      }
     ]
    },
    {
     "title": "Request Latency",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "topk(10,kafka_producer_producer_node_metrics_request_latency_avg{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}} -> {{node_id}} (avg.)"
      },
      {
       "expr": "topk(10,kafka_producer_producer_node_metrics_request_latency_max{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}} -> {{node_id}} (max.)"
      }
     ]
    },
    {
     "title": "Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "topk(10,kafka_producer_producer_node_metrics_request_rate{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}} -> {{node_id}}"
      }
     ]
    },
    {
     "title": "Response Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "topk(10,kafka_producer_producer_node_metrics_response_rate{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}} <- {{node_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Per Topic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Byte Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk(10,kafka_producer_producer_topic_metrics_byte_rate{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}} -> {{topic}}"
      }
     ]
    },
    {
     "title": "Compression Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "topk(10,kafka_producer_producer_topic_metrics_compression_rate{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}} -> {{topic}}"
      }
     ]
    },
    {
     "title": "Record Send Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "topk(10,kafka_producer_producer_topic_metrics_record_send_rate{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}} -> {{topic}}"
      }
     ]
    },
    {
     "title": "Record Retry Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "topk(10,kafka_producer_producer_topic_metrics_record_retry_rate{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}} -> {{topic}}"
      }
     ]
    },
    {
     "title": "Record Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "topk(10,kafka_producer_producer_topic_metrics_record_error_rate{namespace=\"$env\",client_id=~\"$client_id\", pod=~\"$server\"})",
       "legendFormat": "{{client_id}}@{{pod}} -> {{topic}}"
      }
     ]
    }
   ]
  }
 ]
}