{
 "title": "Kafka Connect cluster - v2",
 "description": "Overview of the Kafka Connect cluster",
 "tags": [
  "confluent",
  "kafka-connect"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": "label_values(namespace)" },
   {
    "name": "connect_cluster",
    "label": "Connect cluster",
    "query": "label_values(kafka_connect_connect_worker_metrics_connector_total_task_count{namespace=\"$env\"}, app)"
   },
   {
    "name": "connect_worker",
    "label": "Connect worker",
    "query": "label_values(kafka_connect_connect_worker_metrics_connector_total_task_count{namespace=\"$env\",app=\"$connect_cluster\"}, pod)"
   },
   {
    "name": "connector",
    "label": "Connector",
    "query": "label_values(kafka_connect_connect_worker_metrics_connector_total_task_count{namespace=\"$env\",app=\"$connect_cluster\"}, connector)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connect: Online Workers",
   "type": "stat",
   "description": "Kafka Connect online workers returning metrics.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kafka_connect_app_info{namespace=\"$env\",app=\"$connect_cluster\",version!=\"\"})"
    }
   ]
  },
  {
   "title": "Connect: Sum of Total Tasks",
   "type": "stat",
   "description": "Number of tasks deployed on Kafka Connect cluster.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_total_task_count{namespace=\"$env\",app=\"$connect_cluster\"})"
    }
   ]
  },
  {
   "title": "Connect: Sum of Running Tasks",
   "type": "stat",
   "description": "Number of Running Tasks on the Kafka Connect cluster.\n            Ideally, this number should be equal to the total number of tasks deployed.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_running_task_count{namespace=\"$env\",app=\"$connect_cluster\"})"
    }
   ]
  },
  {
   "title": "Connect: Sum of Paused Tasks",
   "type": "stat",
   "description": "Number of Paused Tasks on the Kafka Connect cluster.\n            Ideally, this number should be zero, as tasks should be running.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_paused_task_count{namespace=\"$env\",app=\"$connect_cluster\"})"
    }
   ]
  },
  {
   "title": "Connect: Sum of Failed Tasks",
   "type": "stat",
   "description": "Number of Paused Tasks on the Kafka Connect cluster.\n            Ideally, this number should be zero, as tasks should be running.\n            It's recommended alerting when this value is higher than 0.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_failed_task_count{namespace=\"$env\",app=\"$connect_cluster\"})"
    }
   ]
  },
  {
   "title": "Connect: Time since last rebalance",
   "type": "stat",
   "description": "Informative value. Time since last rebalance.\n            When this value is continuously and repeatedly low means some connectors are failing and rebalancing is triggered constantly.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "clockms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_rebalance_metrics_time_since_last_rebalance_ms{namespace=\"$env\",app=\"$connect_cluster\"} >= 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Connect Workers",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "kafka_connect_app_info{namespace=\"$env\",app=\"$connect_cluster\",start_time_ms!=\"\"}"
    },
    {
     "expr": "kafka_connect_app_info{namespace=\"$env\",app=\"$connect_cluster\",version!=\"\"}"
    },
    {
     "expr": "sum by (pod) (kafka_connect_connect_worker_metrics_connector_count{namespace=\"$env\",app=\"$connect_cluster\"})"
    },
    {
     "expr": "sum by (pod) (kafka_connect_connect_worker_metrics_connector_startup_success_total{namespace=\"$env\",app=\"$connect_cluster\"})"
    },
    {
     "expr": "sum by (pod) (kafka_connect_connect_worker_metrics_connector_startup_failure_total{namespace=\"$env\",app=\"$connect_cluster\"})"
    },
    {
     "expr": "sum by (pod) (kafka_connect_connect_worker_metrics_task_count{namespace=\"$env\",app=\"$connect_cluster\"})"
    },
    {
     "expr": "sum by (pod) (kafka_connect_connect_worker_metrics_task_startup_success_total{namespace=\"$env\",app=\"$connect_cluster\"})"
    },
    {
     "expr": "sum by (pod) (kafka_connect_connect_worker_metrics_task_startup_failure_total{namespace=\"$env\",app=\"$connect_cluster\"})"
    }
   ]
  },
  {
   "title": "Connectors",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "kafka_connect_connector_info{namespace=\"$env\",app=\"$connect_cluster\"}"
    },
    {
     "expr": "sum by (connector) (kafka_connect_connect_worker_metrics_connector_total_task_count{namespace=\"$env\",app=\"$connect_cluster\"})"
    },
    {
     "expr": "sum by (connector) (kafka_connect_connect_worker_metrics_connector_running_task_count{namespace=\"$env\",app=\"$connect_cluster\"})"
    },
    {
     "expr": "sum by (connector) (kafka_connect_connect_worker_metrics_connector_failed_task_count{namespace=\"$env\",app=\"$connect_cluster\"})"
    },
    {
     "expr": "sum by (connector) (kafka_connect_connect_worker_metrics_connector_paused_task_count{namespace=\"$env\",app=\"$connect_cluster\"})"
    }
   ]
  },
  {
   "title": "Tasks Running Ratio",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_running_ratio{namespace=\"$env\",app=\"$connect_cluster\"}",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Rebalance Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_rebalance_metrics_rebalance_avg_time_ms{namespace=\"$env\",app=\"$connect_cluster\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "Rate of CPU seconds used by the Java process.\n            100% usage represents one core. \n            If there are multiple cores, the total capacity should be 100% * number_cores.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{namespace=\"$env\",app=\"$connect_cluster\",pod=~\"$connect_worker\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Sum of JVM memory used, without including areas (e.g. heap size).",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{namespace=\"$env\",app=\"$connect_cluster\",pod=~\"$connect_worker\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC collection",
   "type": "timeseries",
   "description": "Sum of seconds used by Garbage Collection.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(gc)(irate(jvm_gc_collection_seconds_sum{namespace=\"$env\",app=\"$connect_cluster\",pod=~\"$connect_worker\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Batch Size (Avg.)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kafka_connect_connector_task_metrics_batch_size_avg{namespace=\"$env\",app=\"$connect_cluster\",pod=~\"$connect_worker\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}[{{task}}]"
      }
     ]
    },
    {
     "title": "Batch Size (Max.)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kafka_connect_connector_task_metrics_batch_size_max{namespace=\"$env\",app=\"$connect_cluster\",pod=~\"$connect_worker\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}[{{task}}]"
      }
     ]
    },
    {
     "title": "Offset commit success %",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "kafka_connect_connector_task_metrics_offset_commit_success_percentage{namespace=\"$env\",app=\"$connect_cluster\",pod=~\"$connect_worker\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}[{{task}}]"
      }
     ]
    },
    {
     "title": "Offset commit avg. latency",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_connect_connector_task_metrics_offset_commit_avg_time_ms{namespace=\"$env\",app=\"$connect_cluster\",pod=~\"$connect_worker\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}[{{task}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Record Failures",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "kafka_connect_task_error_metrics_total_record_failures{namespace=\"$env\",app=\"$connect_cluster\",pod=~\"$connect_worker\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}[{{task}}]"
      }
     ]
    },
    {
     "title": "Total Record Error",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 8 },
     "targets": [
      {
       "expr": "kafka_connect_task_error_metrics_total_record_errors{namespace=\"$env\",app=\"$connect_cluster\",pod=~\"$connect_worker\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}[{{task}}]"
      }
     ]
    },
    {
     "title": "Total Records Skipped",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 8 },
     "targets": [
      {
       "expr": "kafka_connect_task_error_metrics_total_records_skipped{namespace=\"$env\",app=\"$connect_cluster\",pod=~\"$connect_worker\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}[{{task}}]"
      }
     ]
    },
    {
     "title": "Total Errors Logged",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "kafka_connect_task_error_metrics_total_errors_logged{namespace=\"$env\",app=\"$connect_cluster\",pod=~\"$connect_worker\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}[{{task}}]"
      }
     ]
    },
    {
     "title": "Total Retries",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 9 },
     "targets": [
      {
       "expr": "kafka_connect_task_error_metrics_total_retries{namespace=\"$env\",app=\"$connect_cluster\",pod=~\"$connect_worker\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}[{{task}}]"
      }
     ]
    },
    {
     "title": "Dead Letter Topic Requests",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 9 },
     "targets": [
      {
       "expr": "kafka_connect_task_error_metrics_deadletterqueue_produce_requests{namespace=\"$env\",app=\"$connect_cluster\",pod=~\"$connect_worker\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}[{{task}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Source Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Poll Batch Avg. Latency",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_connect_source_task_metrics_poll_batch_avg_time_ms{namespace=\"$env\",app=\"$connect_cluster\",pod=~\"$connect_worker\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}[{{task}}]"
      }
     ]
    },
    {
     "title": "Poll Batch Max. Latency",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_connect_source_task_metrics_poll_batch_max_time_ms{namespace=\"$env\",app=\"$connect_cluster\",pod=~\"$connect_worker\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}[{{task}}]"
      }
     ]
    },
    {
     "title": "Source Record Poll Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "kafka_connect_source_task_metrics_source_record_poll_rate{namespace=\"$env\",app=\"$connect_cluster\",pod=~\"$connect_worker\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}[{{task}}]"
      }
     ]
    },
    {
     "title": "Source Record Write Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "kafka_connect_source_task_metrics_source_record_write_rate{namespace=\"$env\",app=\"$connect_cluster\",pod=~\"$connect_worker\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}[{{task}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Sink Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Put Batch Avg. Latency",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_connect_sink_task_metrics_put_batch_avg_time_ms{namespace=\"$env\",app=\"$connect_cluster\",pod=~\"$connect_worker\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}[{{task}}]"
      }
     ]
    },
    {
     "title": "Put Batch Max. Latency",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_connect_sink_task_metrics_put_batch_max_time_ms{namespace=\"$env\",app=\"$connect_cluster\",pod=~\"$connect_worker\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}[{{task}}]"
      }
     ]
    },
    {
     "title": "Partition Count",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "kafka_connect_sink_task_metrics_partition_count{namespace=\"$env\",app=\"$connect_cluster\",pod=~\"$connect_worker\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}[{{task}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Connect Workers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Incoming Byte Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "kafka_connect_connect_metrics_incoming_byte_rate{namespace=\"$env\",app=\"$connect_cluster\",pod=~\"$connect_worker\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Outgoing Byte Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "kafka_connect_connect_metrics_outgoing_byte_rate{namespace=\"$env\",app=\"$connect_cluster\",pod=~\"$connect_worker\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "IO Ratio",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "kafka_connect_connect_metrics_io_ratio{namespace=\"$env\",app=\"$connect_cluster\",pod=~\"$connect_worker\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Network IO Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "kafka_connect_connect_metrics_network_io_rate{namespace=\"$env\",app=\"$connect_cluster\",pod=~\"$connect_worker\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Active Connections",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "kafka_connect_connect_metrics_connection_count{namespace=\"$env\",app=\"$connect_cluster\",pod=~\"$connect_worker\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Authentications",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 7 },
     "targets": [
      {
       "expr": "kafka_connect_connect_metrics_successful_authentication_rate{namespace=\"$env\",app=\"$connect_cluster\",pod=~\"$connect_worker\"}",
       "legendFormat": "{{pod}} (success)"
      },
      {
       "expr": "kafka_connect_connect_metrics_failed_authentication_total{namespace=\"$env\",app=\"$connect_cluster\",pod=~\"$connect_worker\"}",
       "legendFormat": "{{pod}} (failed)"
      }
     ]
    }
   ]
  }
 ]
}