{
 "title": "Librdkafka Applications",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(kafka_broker_connection_total,application)"
    }
   },
   {
    "name": "clientId",
    "label": "Client Id",
    "query": {
     "query": "label_values(kafka_broker_latency_average_ms, client_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General Consumer Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total number of messages consumed received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "kafka_consumed_total{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"consumer\"}",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Total number of fetch bytes received from Kafka brokers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kafka_bytes_consumed_total{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"consumer\"}",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Rate of number of fetch bytes received from Kafka brokers (5min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 14, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(kafka_bytes_consumed_total{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"consumer\"}[5m])",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Number of ops (callbacks, events, etc) waiting in queue for application to serve with rd_kafka_poll()",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kafka_ops_waiting_queue_total{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"consumer\"}",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Total number of responses received from Kafka brokers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 9 },
     "targets": [
      {
       "expr": "kafka_responses_received_total{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"consumer\"}",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Total number of bytes received from Kafka brokers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 14, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kafka_bytes_received_total{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"consumer\"}",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Time elapsed since last rebalance (assign or revoke)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_rebalance_age{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"consumer\"}",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Total number of rebalances (assign or revoke)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 6, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_rebalance_total{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"consumer\"}",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Rate of number of bytes received from Kafka brokers (5 min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 10, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(kafka_bytes_received_total{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"consumer\"}[5m])",
       "legendFormat": "{{client_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consumer Metrics (per Broker)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Broker Connection Total",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_broker_connection_total{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"consumer\"})",
       "legendFormat": "Broker : {{broker_id}} - Client : {{client_id}}"
      }
     ]
    },
    {
     "title": "Broker Disconnection Total",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 4, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_broker_disconnection_total{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"consumer\"})",
       "legendFormat": "Broker : {{broker_id}} - Client : {{client_id}}"
      }
     ]
    },
    {
     "title": "Broker RTT Latency Average",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 15, "x": 9, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "kafka_broker_latency_average_ms{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"consumer\"}",
       "legendFormat": "Broker : {{broker_id}} - Client : {{client_id}}"
      }
     ]
    },
    {
     "title": "Total number of responses received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "kafka_broker_responses_total{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"consumer\"}",
       "legendFormat": "Broker : {{broker_id}} - Client : {{client_id}}"
      }
     ]
    },
    {
     "title": "Total number of bytes received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kafka_broker_responses_byte_total{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"consumer\"}",
       "legendFormat": "Broker : {{broker_id}} - Client : {{client_id}}"
      }
     ]
    },
    {
     "title": "Total number of receive errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kafka_broker_error_total{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"consumer\"}",
       "legendFormat": "Broker : {{broker_id}} - Client : {{client_id}}"
      }
     ]
    },
    {
     "title": "Rate of number of bytes received (5 min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(kafka_broker_responses_byte_total{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"consumer\"}[5m])",
       "legendFormat": "Broker : {{broker_id}} - Client : {{client_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consumer Metrics (per Topic / Partition)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Batch sizes in bytes average",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kafka_topic_batch_size_bytes_average{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"consumer\"}",
       "legendFormat": "Topic : {{topic}}"
      }
     ]
    },
    {
     "title": "Batch message counts average",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kafka_topic_batch_count_average{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"consumer\"}",
       "legendFormat": "Topic : {{topic}}"
      }
     ]
    },
    {
     "title": "Consumer Lag",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kafka_partition_lag{application=\"$application\", client_id=\"$clientId\", partition_id=~\"^[0-9]*$\", librdkafka_type=\"consumer\"}",
       "legendFormat": "Topic : {{topic}} Partition {{partition_id}}"
      }
     ]
    },
    {
     "title": "Total number of messages consumed",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kafka_partition_message_consumed_total{application=\"$application\", client_id=\"$clientId\", partition_id=~\"^[0-9]*$\", librdkafka_type=\"consumer\"}",
       "legendFormat": "Topic : {{topic}} Partition {{partition_id}}"
      }
     ]
    },
    {
     "title": "Rate of number of messages consumed (5min)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(kafka_partition_message_consumed_total{application=\"$application\", client_id=\"$clientId\", partition_id=~\"^[0-9]*$\", librdkafka_type=\"consumer\"}[5m])",
       "legendFormat": "Topic : {{topic}} Partition {{partition_id}}"
      }
     ]
    },
    {
     "title": "Total number of bytes received for rxmsgs",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kafka_partition_message_bytes_consumed_total{application=\"$application\", client_id=\"$clientId\", partition_id=~\"^[0-9]*$\", librdkafka_type=\"consumer\"}",
       "legendFormat": "Topic : {{topic}} Partition {{partition_id}}"
      }
     ]
    },
    {
     "title": "Rate of number of bytes received for rxmsgs (5min)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(kafka_partition_message_bytes_consumed_total{application=\"$application\", client_id=\"$clientId\", partition_id=~\"^[0-9]*$\", librdkafka_type=\"consumer\"}[5m])",
       "legendFormat": "Topic : {{topic}} Partition {{partition_id}}"
      }
     ]
    }
   ]
  },
  { "title": "General Producer Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Current number of messages in producer queues",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "kafka_message_queue_max{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"producer\"}",
     "legendFormat": "Maximum number of messages allowed allowed on the producer queues"
    },
    {
     "expr": "kafka_messages_queue_current{application=\"$application\", client_id=\"$clientId\"}",
     "legendFormat": "Current number of messages in producer queues"
    }
   ]
  },
  {
   "title": "Current total of bytes in producer queues",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kafka_message_queue_size_bytes_max{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"producer\"}",
     "legendFormat": "Maximum total size of messages allowed on the producer queue"
    },
    {
     "expr": "kafka_messages_queue_size_bytes_total{application=\"$application\", client_id=\"$clientId\"}",
     "legendFormat": "Current total size of messages in producer queues"
    }
   ]
  },
  {
   "title": "Total number of messages and bytes transmitted (produced) to Kafka brokers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_transmitted_message_total{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"producer\"}",
     "legendFormat": "Total number of messages produced"
    },
    {
     "expr": "kafka_transmitted_message_bytes_total{application=\"$application\", client_id=\"$clientId\"}",
     "legendFormat": "Total number of bytes produced"
    }
   ]
  },
  {
   "title": "Rate of number of messages and bytes transmitted (produced) to Kafka brokers (5min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(kafka_transmitted_message_total{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"producer\"}[5m])",
     "legendFormat": "Rate of number of messages produced"
    },
    {
     "expr": "rate(kafka_transmitted_message_bytes_total{application=\"$application\", client_id=\"$clientId\"}[5m])",
     "legendFormat": "Rate of number of bytes produced"
    }
   ]
  },
  {
   "title": "Total number of request and bytes transmitted to Kafka brokers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_transmitted_request_total{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"producer\"}",
     "legendFormat": "Total number of requests sent to Kafka brokers"
    },
    {
     "expr": "kafka_transmited_request_bytes_total{application=\"$application\", client_id=\"$clientId\"}",
     "legendFormat": "Total number of bytes transmitted to Kafka brokers"
    }
   ]
  },
  {
   "title": "Rate of number of request and bytes transmitted to Kafka brokers (5min)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(kafka_transmitted_request_total{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"producer\"}[5m])",
     "legendFormat": "Rate of number of requests sent to Kafka brokers"
    },
    {
     "expr": "rate(kafka_transmited_request_bytes_total{application=\"$application\", client_id=\"$clientId\"}[5m])",
     "legendFormat": "Rate of number of bytes transmitted to Kafka brokers"
    }
   ]
  },
  {
   "title": "Number of ops (callbacks, events, etc) waiting in queue for application to serve with rd_kafka_poll()",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_ops_waiting_queue_total{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"producer\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  { "title": "Producer Metrics (per Broker)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Broker Connection Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_broker_connection_total{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"producer\"})",
     "legendFormat": "Broker : {{broker_id}} - Client : {{client_id}}"
    }
   ]
  },
  {
   "title": "Broker Disconnection Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_broker_disconnection_total{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"producer\"})",
     "legendFormat": "Broker : {{broker_id}} - Client : {{client_id}}"
    }
   ]
  },
  {
   "title": "Broker RTT Latency Average",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "kafka_broker_latency_average_ms{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"producer\"}",
     "legendFormat": "Broker : {{broker_id}} - Client : {{client_id}}"
    }
   ]
  },
  {
   "title": "Internal Producer Queue latency (per broker)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "kafka_broker_internal_queue_latency_ms{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"producer\"}",
     "legendFormat": "Broker : {{broker_id}} - Client : {{client_id}}"
    }
   ]
  },
  {
   "title": "Internal Request Queue Latency (per broker)",
   "type": "timeseries",
   "description": "This is the time between a request is enqueued on the transmit (outbuf) queue and the time the request is written to the TCP socket. Additional buffering and latency may be incurred by the TCP stack and network.",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "kafka_broker_internal_request_queue_latency_ms{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"producer\"}",
     "legendFormat": "Broker : {{broker_id}} - Client : {{client_id}}"
    }
   ]
  },
  {
   "title": "Number of requests awaiting transmission to broker.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_broker_request_awaiting_total{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"producer\"}",
     "legendFormat": "Broker : {{broker_id}} - Client : {{client_id}}"
    }
   ]
  },
  {
   "title": "Number of messages awaiting transmission to broker.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_broker_message_awaiting_total{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"producer\"}",
     "legendFormat": "Broker : {{broker_id}} - Client : {{client_id}}"
    }
   ]
  },
  {
   "title": "Number of requests in-flight (per broker)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_broker_request_in_flight_total{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"producer\"}",
     "legendFormat": "Broker : {{broker_id}} - Client : {{client_id}}"
    }
   ]
  },
  {
   "title": "Number of messages in-flight (per broker)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_broker_message_in_flight_total{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"producer\"}",
     "legendFormat": "Broker : {{broker_id}} - Client : {{client_id}}"
    }
   ]
  },
  {
   "title": "Total number of bytes sent (per broker)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kafka_broker_request_sent_bytes_total{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"producer\"}",
     "legendFormat": "Broker : {{broker_id}} - Client : {{client_id}}"
    }
   ]
  },
  {
   "title": "Rate of number of bytes sent (per broker) (5min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kafka_broker_request_sent_bytes_total{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"producer\"}[5m])",
     "legendFormat": "Broker : {{broker_id}} - Client : {{client_id}}"
    }
   ]
  },
  {
   "title": "Total number of requests sent (per broker)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_broker_request_sent_total{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"producer\"}",
     "legendFormat": "Broker : {{broker_id}} - Client : {{client_id}}"
    }
   ]
  },
  {
   "title": "Rate of number of requests sent (per broker) (5min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(kafka_broker_request_sent_total{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"producer\"}[5m])",
     "legendFormat": "Broker : {{broker_id}} - Client : {{client_id}}"
    }
   ]
  },
  {
   "title": "Total number of request retries (per broker)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_broker_retries_total{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"producer\"}",
     "legendFormat": "Broker : {{broker_id}} - Client : {{client_id}}"
    }
   ]
  },
  {
   "title": "Total number of requests timed out (per broker)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_broker_timeout_total{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"producer\"}",
     "legendFormat": "Broker : {{broker_id}} - Client : {{client_id}}"
    }
   ]
  },
  {
   "title": "Producer Metrics (per Topic / Partition)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 }
  },
  {
   "title": "Batch sizes in bytes average",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kafka_topic_batch_size_bytes_average{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"producer\"}",
     "legendFormat": "Topic : {{topic}}"
    }
   ]
  },
  {
   "title": "Batch message counts average",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_topic_batch_count_average{application=\"$application\", client_id=\"$clientId\", librdkafka_type=\"producer\"}",
     "legendFormat": "Topic : {{topic}}"
    }
   ]
  },
  {
   "title": "Current number of messages in-flight to/from broker",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_partition_message_in_flight_total{application=\"$application\", client_id=\"$clientId\", partition_id=~\"^[0-9]*$\", librdkafka_type=\"producer\"}",
     "legendFormat": "Topic {{topic}} Partition {{partition_id}}"
    }
   ]
  },
  {
   "title": "Total number of bytes transmitted for txmsgs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kafka_partition_transmitted_message_bytes_total{application=\"$application\", client_id=\"$clientId\", partition_id=~\"^[0-9]*$\", librdkafka_type=\"producer\"}",
     "legendFormat": "Topic {{topic}} Partition {{partition_id}}"
    }
   ]
  },
  {
   "title": "Rate of number of bytes transmitted for txmsgs (5min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kafka_partition_transmitted_message_bytes_total{application=\"$application\", client_id=\"$clientId\", partition_id=~\"^[0-9]*$\", librdkafka_type=\"producer\"}[5m])",
     "legendFormat": "Topic {{topic}} Partition {{partition_id}}"
    }
   ]
  },
  {
   "title": "Total number of messages transmitted (produced)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_partition_transmitted_message_total{application=\"$application\", client_id=\"$clientId\", partition_id=~\"^[0-9]*$\", librdkafka_type=\"producer\"}",
     "legendFormat": "Topic {{topic}} Partition {{partition_id}}"
    }
   ]
  },
  {
   "title": "Rate of number of messages transmitted for txmsgs (5min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(kafka_partition_transmitted_message_total{application=\"$application\", client_id=\"$clientId\", partition_id=~\"^[0-9]*$\", librdkafka_type=\"producer\"}[5m])",
     "legendFormat": "Topic {{topic}} Partition {{partition_id}}"
    }
   ]
  }
 ]
}