{
 "title": "Flink Cluster (Job Manager)",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(up{job=\"flink\"},env)"
    }
   },
   {
    "name": "flink_cluster_id",
    "label": "Cluster ID",
    "query": {
     "query": "label_values(up{job=\"flink\"},flink_cluster_id)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(flink_jobmanager_Status_JVM_CPU_Load{job=\"flink\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster (Job Manager)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Registered Task Managers",
   "type": "stat",
   "description": "The number of registered taskmanagers.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flink_jobmanager_numRegisteredTaskManagers{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", pod=~\"$pod\"})",
     "legendFormat": "{{ksql_cluster}}"
    }
   ]
  },
  {
   "title": "Total Pending Task Managers",
   "type": "stat",
   "description": "The number of pending taskmanagers.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flink_jobmanager_numPendingTaskManagers{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", pod=~\"$pod\"})\n",
     "legendFormat": "{{ksql_cluster}}"
    }
   ]
  },
  {
   "title": "Total Running Jobs",
   "type": "stat",
   "description": "The number of running jobs",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flink_jobmanager_numRunningJobs{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", pod=~\"$pod\"})",
     "legendFormat": "{{ksql_cluster}}"
    }
   ]
  },
  {
   "title": "Max Total Checkpoint Count",
   "type": "stat",
   "description": "The checkpointed size of the last checkpoint (in bytes), this metric could be different from lastCheckpointFullSize if incremental checkpoint or changelog is enabled.\t",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(flink_jobmanager_job_totalNumberOfCheckpoints{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", pod=~\"$pod\"})\n\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Task Slots",
   "type": "stat",
   "description": "The total number of task slots.\t",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flink_jobmanager_taskSlotsTotal{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", pod=~\"$pod\"})",
     "legendFormat": "{{ksql_cluster}}"
    }
   ]
  },
  {
   "title": "Total Restarts",
   "type": "stat",
   "description": "The total number of restarts since this job was submitted, including full restarts and fine-grained restarts.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flink_jobmanager_job_numRestarts{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", pod=~\"$pod\"})",
     "legendFormat": "{{ksql_cluster}}"
    }
   ]
  },
  {
   "title": "Job with Min Uptime",
   "type": "stat",
   "description": "Job Manager uptime\n",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(flink_jobmanager_job_runningTime{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", pod=~\"$pod\"})\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Checkpoint Latency",
   "type": "stat",
   "description": "The time it took to complete the last checkpoint (in milliseconds).",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(flink_jobmanager_job_lastCheckpointDuration{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", pod=~\"$pod\"})\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Max Last Checkpoint Size of all jobs",
   "type": "stat",
   "description": "The checkpointed size of the last checkpoint (in bytes), this metric could be different from lastCheckpointFullSize if incremental checkpoint or changelog is enabled.\t",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(flink_jobmanager_job_lastCheckpointSize{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", pod=~\"$pod\"})\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Available Task Slots",
   "type": "stat",
   "description": "The number of available task slots.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flink_jobmanager_taskSlotsAvailable{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", pod=~\"$pod\"})",
     "legendFormat": "{{ksql_cluster}}"
    }
   ]
  },
  {
   "title": "Max Checkpoint Error Rate",
   "type": "stat",
   "description": "Checkpoint completion rate calculated by (numberOfFailedCheckpoints) / (totalNumberOfCheckpoints)",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(flink_jobmanager_job_numberOfFailedCheckpoints{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", pod=~\"$pod\"} / flink_jobmanager_job_totalNumberOfCheckpoints{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", pod=~\"$pod\"})\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Max CPU Load",
   "type": "stat",
   "description": "Checkpoint completion rate calculated by (numberOfFailedCheckpoints) / (totalNumberOfCheckpoints)",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(flink_jobmanager_Status_JVM_CPU_Load{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Job Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Checkpoints Failure Rate by Job",
   "type": "table",
   "description": "Checkpoints Failure Rate by Job",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "flink_jobmanager_job_numberOfFailedCheckpoints{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", pod=~\"$pod\"} / flink_jobmanager_job_totalNumberOfCheckpoints{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", pod=~\"$pod\"}\n\n",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Total Checkpoints by Job",
   "type": "table",
   "description": "Total Checkpoints by Job",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "flink_jobmanager_job_totalNumberOfCheckpoints{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", pod=~\"$pod\"}\n",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Uptime by Job",
   "type": "table",
   "description": "Job by Uptime",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "flink_jobmanager_job_runningTime{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", pod=~\"$pod\"}\n",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Checkpoint Size by Job",
   "type": "table",
   "description": "Checkpoint Size by Job",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_jobmanager_job_lastCheckpointSize{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", pod=~\"$pod\"}\n",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Checkpoint Latency by Job",
   "type": "table",
   "description": "Checkpoint Latency by Job",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "flink_jobmanager_job_lastCheckpointDuration{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", pod=~\"$pod\"}\n",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Total Restarts",
   "type": "timeseries",
   "description": "Total Restarts",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(flink_jobmanager_job_numRestarts{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "CPU & Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "description": "CPU Load",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_CPU_Load{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM Threads Count",
   "type": "timeseries",
   "description": "JVM Threads Count",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(flink_jobmanager_Status_JVM_CPU_Time{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", pod=~\"$pod\"}[1m])  / 1e9\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Memory Used",
   "type": "timeseries",
   "description": "Total Memory Used by adding used heap and non heap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Used{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", pod=~\"$pod\"} + flink_jobmanager_Status_JVM_Memory_NonHeap_Used{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", pod=~\"$pod\"}",
     "legendFormat": "Total Memory Used"
    },
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Used{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", pod=~\"$pod\"}",
     "legendFormat": "Heap Used"
    }
   ]
  },
  { "title": "Checkpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Checkpoint Duration",
   "type": "timeseries",
   "description": "The time it took to complete the last checkpoint (in milliseconds).",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(flink_jobmanager_job_lastCheckpointDuration{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", pod=~\"$pod\"})\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Last Checkpoint Size",
   "type": "timeseries",
   "description": "The checkpointed size of the last checkpoint (in bytes), this metric could be different from lastCheckpointFullSize if incremental checkpoint or changelog is enabled.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_jobmanager_job_lastCheckpointSize{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", pod=~\"$pod\"}\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Last Checkpoint Full Size",
   "type": "timeseries",
   "description": "The full size of the last checkpoint (in bytes).",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_jobmanager_job_lastCheckpointFullSize{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", pod=~\"$pod\"}\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Number of Failed Checkpoints",
   "type": "timeseries",
   "description": "The number of failed checkpoints.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "flink_jobmanager_job_numberOfFailedCheckpoints{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", pod=~\"$pod\"}\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of Failed Checkpoints per minute",
   "type": "timeseries",
   "description": "The number of failed checkpoints.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(flink_jobmanager_job_numberOfFailedCheckpoints{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", pod=~\"$pod\"}[1m])*60\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Number of Checkpoints per minute",
   "type": "timeseries",
   "description": "The number of total checkpoints (in progress, completed, failed).\n",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(flink_jobmanager_job_totalNumberOfCheckpoints{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", pod=~\"$pod\"}[1m])*60\n",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}