{
 "title": "Flink Cluster (Task Manager)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(up{job=\"flink\"},env)"
    }
   },
   {
    "name": "flink_cluster_id",
    "label": "Cluster ID",
    "query": {
     "query": "label_values(up{job=\"flink\"},flink_cluster_id)"
    }
   },
   {
    "name": "jobid",
    "label": "Job ID",
    "query": {
     "query": "label_values(flink_taskmanager_job_task_numBytesIn{job=\"flink\"},job_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster (Task Manager)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Tasks",
   "type": "stat",
   "description": "The number of tasks",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(flink_taskmanager_job_task_initializationTime{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"})\n",
     "legendFormat": "{{ksql_cluster}}"
    }
   ]
  },
  {
   "title": "Backpressured Task Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_isBackPressured{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"})\n",
     "legendFormat": "{{ksql_cluster}}"
    }
   ]
  },
  {
   "title": "Record Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_numRecordsInErrors{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"})",
     "legendFormat": "{{ksql_cluster}}"
    }
   ]
  },
  {
   "title": "Max CPU Load",
   "type": "stat",
   "description": "Checkpoint completion rate calculated by (numberOfFailedCheckpoints) / (totalNumberOfCheckpoints)",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(flink_taskmanager_Status_JVM_CPU_Load{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Records In Per Sec",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_numRecordsInPerSecond{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"})",
     "legendFormat": "{{ksql_cluster}}"
    }
   ]
  },
  {
   "title": "Total Records Out Per Sec",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_numRecordsOutPerSecond{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"})",
     "legendFormat": "{{ksql_cluster}}"
    }
   ]
  },
  {
   "title": "Backpressure by Task",
   "type": "table",
   "description": "Job by Uptime",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_isBackPressured{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"}",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Max GC Time Ratio pre Sec",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(flink_taskmanager_Status_JVM_GarbageCollector_All_TimeMsPerSecond\n{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\"} )\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Max Busy Time Ratio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(flink_taskmanager_job_task_busyTimeMsPerSecond{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"} / 1000)\n",
     "legendFormat": "{{ksql_cluster}}"
    }
   ]
  },
  {
   "title": "Max Backpressured Time Ratio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(flink_taskmanager_job_task_backPressuredTimeMsPerSecond{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"} / 1000)\n",
     "legendFormat": "{{ksql_cluster}}"
    }
   ]
  },
  { "title": "Kafka Consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Consumer Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_lag_max{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"}",
     "legendFormat": "{{job_name}} - {{operator_name}}"
    }
   ]
  },
  {
   "title": "Records Consumed Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_consumed_rate{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"}",
     "legendFormat": "{{job_name}} - {{operator_name}}"
    }
   ]
  },
  {
   "title": "Bytes Consumed Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_bytes_consumed_rate{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"}",
     "legendFormat": "{{job_name}} - {{operator_name}}"
    }
   ]
  },
  {
   "title": "Records per Request Avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_per_request_avg{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"}",
     "legendFormat": "{{job_name}} - {{operator_name}}"
    }
   ]
  },
  { "title": "Kafka Producer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Record Send Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaProducer_record_send_rate{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"}",
     "legendFormat": "{{job_name}} - {{operator_name}}"
    }
   ]
  },
  {
   "title": "Outgoing Byte Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaProducer_outgoing_byte_rate{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"}",
     "legendFormat": "{{job_name}} - {{operator_name}}"
    }
   ]
  },
  {
   "title": "Batch Size Avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaProducer_batch_size_avg{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"}",
     "legendFormat": "{{job_name}} - {{operator_name}}"
    }
   ]
  },
  {
   "title": "Request Latency Avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaProducer_request_latency_avg{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"}",
     "legendFormat": "{{job_name}} - {{operator_name}}"
    }
   ]
  },
  {
   "title": "Task",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "backpressured",
     "type": "timeseries",
     "description": "Whether the task is back-pressured.\t",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 134 },
     "fieldConfig": { "defaults": { "unit": "bool" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_isBackPressured{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"}\n",
       "legendFormat": "{{task_id}} - {{task_name}}"
      }
     ]
    },
    {
     "title": "Busy Time Ratio",
     "type": "timeseries",
     "description": "The time (in milliseconds) this task is busy (neither idle nor back pressured) per second. Can be NaN, if the value could not be calculated.\t",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 134 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_busyTimeMsPerSecond{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"} / 1000",
       "legendFormat": "{{task_id}} - {{task_name}}"
      }
     ]
    },
    {
     "title": "Backpressured Time",
     "type": "timeseries",
     "description": "The time (in milliseconds) this task is back pressured (soft or hard) per second. It's a sum of softBackPressuredTimeMsPerSecond and hardBackPressuredTimeMsPerSecond.\tThis is divided by 1000ms to show the ratio.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 134 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_backPressuredTimeMsPerSecond{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"} / 1000",
       "legendFormat": "{{task_id}} - {{task_name}}"
      }
     ]
    },
    {
     "title": "Hard Backpressured Ratio",
     "type": "timeseries",
     "description": "Busy Time Ratio calculated by dividing busyTimeMsPerSecond by 1000\n ",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 356 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_hardBackPressuredTimeMsPerSecond{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"} / 1000",
       "legendFormat": "{{task_id}} - {{task_name}}"
      }
     ]
    },
    {
     "title": "Num Records In per Sec",
     "type": "timeseries",
     "description": "The total number of records this operator/task has received.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 356 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_numRecordsInPerSecond{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"}\n",
       "legendFormat": "{{task_id}} - {{task_name}}"
      }
     ]
    },
    {
     "title": "Num Records Out per Sec",
     "type": "timeseries",
     "description": "The number of records this operator/task sends per second.\t",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 356 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_numRecordsOutPerSecond{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"}\n",
       "legendFormat": "{{task_id}} - {{task_name}}"
      }
     ]
    }
   ]
  },
  { "title": "CPU & Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "description": "CPU Load",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_CPU_Load{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\"}\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Memory Used",
   "type": "timeseries",
   "description": "Total Memory Used by adding used heap and non heap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Used{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\"} + flink_taskmanager_Status_JVM_Memory_NonHeap_Used{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\"}",
     "legendFormat": "Total Memory Used - {{pod}}"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Used{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\"}\n",
     "legendFormat": "Heap Used - {{pod}}"
    }
   ]
  },
  {
   "title": "GC Time Spent per Second (ms)",
   "type": "timeseries",
   "description": "The time (in milliseconds) spent garbage collecting per second for the given (or all) collector.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_GarbageCollector_All_TimeMsPerSecond\n{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\"} \n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Live Threads Count",
   "type": "timeseries",
   "description": "Live Threads Count",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Threads_Count{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\"} \n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Num Bytes In Local per Sec",
     "type": "timeseries",
     "description": "The total number of bytes this task has read from a local source.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 154 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_numBytesInLocalPerSecond{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"}\n",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Num Bytes Remote In per Second",
     "type": "timeseries",
     "description": "The number of bytes this task reads from a remote source per second.\t",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 154 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_numBytesInRemotePerSecond{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"}\n",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Num Bytes Remote per Second",
     "type": "timeseries",
     "description": "The number of bytes this task reads from a remote source per second.\t",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 154 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_numBytesInRemotePerSecond{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"}\n",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Num Buffers Local In Per Sec",
     "type": "timeseries",
     "description": "The number of network buffers this task reads from a local source per second.\t",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Input_numBuffersInLocalPerSecond{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"}\n",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Num Buffers Remote In Per Sec",
     "type": "timeseries",
     "description": "The number of network buffers this task reads from a remote source per second.\t",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Input_numBuffersInRemotePerSecond{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"}\n",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Queued Input Buffer Size",
     "type": "timeseries",
     "description": "The number of queued input buffers. (ignores LocalInputChannels which are using blocking subpartitions)",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_buffers_inputQueueSize{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Num Bytes Out per Sec",
     "type": "timeseries",
     "description": "The number of bytes this task emits per second.\t",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 170 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_numBytesOutPerSecond{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"}\n",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Num Buffers Out per Sec",
     "type": "timeseries",
     "description": "The number of network buffers this task emits per second.\t",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 170 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_numBuffersOutPerSecond{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"}\n",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Available Memory Segments (%)",
     "type": "timeseries",
     "description": "Available Memory Segments by taking available and divided by total",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 155 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_Network_AvailableMemorySegments{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\"}\n/ flink_taskmanager_Status_Network_TotalMemorySegments{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\"}\n",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Queued Input Buffers",
     "type": "timeseries",
     "description": "The number of queued input buffers. (ignores LocalInputChannels which are using blocking subpartitions)",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 155 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_buffers_inputQueueLength{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Queued Output Buffers",
     "type": "timeseries",
     "description": "The number of queued output buffers. (ignores LocalInputChannels which are using blocking subpartitions)",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 155 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_buffers_outputQueueSize{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Queued Input Size",
     "type": "timeseries",
     "description": "The real size of queued input buffers in bytes. The size for local input channels is always `0` since the local channel takes records directly from the output queue.\t",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_buffers_inputQueueSize{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Queued Output Size",
     "type": "timeseries",
     "description": "The size of queued output buffers. (ignores LocalInputChannels which are using blocking subpartitions)",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_buffers_outputQueueSize{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RocksDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "RocksDB Number of Keys (estimate)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 98 },
     "targets": [
      {
       "expr": "{__name__=~\"flink_taskmanager_job_task_operator_.*_rocksdb_estimate_num_keys\", job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"}",
       "legendFormat": "{{job_name}} - {{operator_name}}"
      }
     ]
    },
    {
     "title": "RocksDB Bytes Read (Uncompressed)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_operator_rocksdb_bytes_read{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"}[1m])",
       "legendFormat": "{{job_name}} - {{operator_name}}"
      }
     ]
    },
    {
     "title": "RocksDB Bytes Written (Uncompressed)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_operator_rocksdb_bytes_written{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"}[1m])",
       "legendFormat": "{{job_name}} - {{operator_name}}"
      }
     ]
    },
    {
     "title": "RocksDB Block Cache Capacity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "{__name__=~\"flink_taskmanager_job_task_operator_.*_rocksdb_block_cache_capacity\", job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"}",
       "legendFormat": "{{job_name}} - {{operator_name}}"
      }
     ]
    },
    {
     "title": "RocksDB Block Cache Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "{__name__=~\"flink_taskmanager_job_task_operator.*rocksdb_block_cache_usage\", job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"}",
       "legendFormat": "{{job_name}} - {{operator_name}}"
      }
     ]
    },
    {
     "title": "RocksDB Background Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 106 },
     "targets": [
      {
       "expr": "{__name__=~\"flink_taskmanager_job_task_operator_.*_rocksdb_background_errors\", job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"}",
       "legendFormat": "{{job_name}} - {{operator_name}}"
      }
     ]
    },
    {
     "title": "RocksDB Block Cache Hit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 114 },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_operator_rocksdb_block_cache_hit{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"}",
       "legendFormat": "Left: {{job_name}} - {{operator_name}}"
      }
     ]
    },
    {
     "title": "RocksDB Block Cache Miss",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 114 },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_operator_rocksdb_block_cache_miss{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"}",
       "legendFormat": "Left: {{job_name}} - {{operator_name}}"
      }
     ]
    },
    {
     "title": "RocksDB Block Cache Hit Ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_operator_rocksdb_block_cache_hit{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"} / (flink_taskmanager_job_task_operator_rocksdb_block_cache_miss{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"} + flink_taskmanager_job_task_operator_rocksdb_block_cache_hit{job=\"flink\", env=\"$env\", flink_cluster_id=~\"$flink_cluster_id\", job_id=~\"$jobid\"})",
       "legendFormat": "Left: {{job_name}} - {{operator_name}}"
      }
     ]
    }
   ]
  },
  { "title": "State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Watermark Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_watermarkLag\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get/Write/Clear Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_state_name_mapStatePutLatency{quantile=\"0.99\"}\n",
     "legendFormat": "Put - {{label_name}} {{job_name}} {{task_name}}"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_state_name_stateClearLatency{quantile=\"0.99\"}\n",
     "legendFormat": "Clear - {{label_name}} {{job_name}} {{task_name}}"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_state_name_valueStateGetLatency{quantile=\"0.99\"}\n",
     "legendFormat": "Get - {{label_name}} {{job_name}} {{task_name}}"
    }
   ]
  }
 ]
}