{
 "title": "GlobalKTable",
 "description": "GlobalKTable Metrics derived from Kafka Streams JMX metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(kafka_streams_stream_metrics,env)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_streams_stream_metrics,instance)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(kafka_streams_stream_metrics,job)"
    }
   },
   {
    "name": "application_id",
    "label": "application_id",
    "query": {
     "query": "label_values(kafka_streams_stream_metrics,application_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Clients Running",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_streams_stream_metrics{state=\"RUNNING\", instance=\"$instance\", job=\"$job\", env=\"$env\", client_id=~\"$application_id.*\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max CPU Core Usage",
   "type": "stat",
   "description": "Maximum of CPU Core Usage of all selected instances",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rate(kafka_consumer_consumer_metrics_io_ratio{instance=\"$instance\", job=\"$job\", env=\"$env\", client_id=~\"$application_id.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Stream Threads",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kafka_streams_stream_state_metrics_background_errors{instance=\"$instance\", job=\"$job\", env=\"$env\", thread_id=~\"$application_id.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Records Processed per Second Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_streams_stream_processor_node_metrics_process_rate{instance=\"$instance\", job=\"$job\", env=\"$env\", thread_id=~\"$application_id.*\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Dropped Records",
   "type": "stat",
   "description": "The total number of records dropped for all tasks.",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum(kafka_streams_stream_task_metrics_dropped_records{instance=\"$instance\", job=\"$job\", env=\"$env\", thread_id=~\"$application_id.*\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Consumer Lag",
   "type": "stat",
   "description": "Max Consumer Lag of all selected instances",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kafka_consumer_consumer_fetch_manager_metrics_records_lag_max{instance=\"$instance\", job=\"$job\", env=\"$env\", client_id=~\"$application_id.*\", topic!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU IO Ratio",
     "type": "timeseries",
     "description": "Fraction of time the I/O thread spent actively doing I/O",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_io_ratio{instance=\"$instance\", job=\"$job\", env=\"$env\", client_id=~\"$application_id.*\"}",
       "legendFormat": "{{app}} - {{instance}}"
      }
     ]
    },
    {
     "title": "CPU IO Wait Ratio",
     "type": "timeseries",
     "description": "Fraction of time the I/O thread spent waiting for I/O",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_io_wait_ratio{instance=\"$instance\", job=\"$job\", env=\"$env\", client_id=~\"$application_id.*\"}",
       "legendFormat": "{{app}} - {{instance}}"
      }
     ]
    },
    {
     "title": "CPU Core Usage",
     "type": "timeseries",
     "description": "The number of CPU cores is this process using, on average, over the last 5 minutes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{instance=\"$instance\", job=\"$job\", env=\"$env\"}[5m])",
       "legendFormat": "{{app}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Memory Used (%)",
     "type": "timeseries",
     "description": "Memory used in percentage of max",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{area=\"heap\"} / jvm_memory_max_bytes{area=\"heap\"}",
       "legendFormat": "Heap - {{instance}}"
      },
      {
       "expr": "jvm_memory_used_bytes{area=\"nonheap\"} / jvm_memory_max_bytes{area=\"nonheap\"}",
       "legendFormat": "NonHeap - {{instance}}"
      }
     ]
    },
    {
     "title": "Max Memory",
     "type": "timeseries",
     "description": "Max (bytes) of a given JVM memory area",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_max_bytes{area=\"heap\"}",
       "legendFormat": "Heap {{instance}}"
      },
      {
       "expr": "jvm_memory_max_bytes{area=\"nonheap\"}",
       "legendFormat": "NonHeap: {{instance}}"
      }
     ]
    },
    {
     "title": "Memory Used Bytes",
     "type": "timeseries",
     "description": "Memory used bytes for heap and nonheap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{area=\"heap\"}",
       "legendFormat": "Heap {{instance}}"
      },
      {
       "expr": "jvm_memory_used_bytes{area=\"nonheap\"}",
       "legendFormat": "NonHeap: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka Streams",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka Streams Alive/Failed Stream Threads",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "kafka_streams_stream_metrics{alive_stream_threads != \"\", instance=\"$instance\", job=\"$job\", env=\"$env\", client_id=~\"$application_id.*\"}",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": " kafka_streams_stream_metrics{failed_stream_threads != \"\", instance=\"$instance\", job=\"$job\", env=\"$env\", client_id=~\"$application_id.*\"}",
       "legendFormat": "{{a}}"
      }
     ]
    },
    {
     "title": "Kafka Streams Client State",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "kafka_streams_stream_metrics{client_id!=\"\", state!=\"\", env=\"$env\", }",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Number of Running Clients",
     "type": "timeseries",
     "description": "Number of clients with state = RUNNING",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kafka_streams_stream_metrics{state=\"RUNNING\", instance=\"$instance\", job=\"$job\", env=\"$env\", client_id=~\"$application_id.*\"})",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "description": "Total number of background errors",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_background_errors{instance=\"$instance\", job=\"$job\", env=\"$env\", thread_id=~\"$application_id.*\"}",
       "legendFormat": "Background - {{app}} {{instance}} {{thread_id}} {{task_id}}"
      },
      {
       "expr": "kafka_streams_stream_state_metrics_number_file_errors{instance=\"$instance\", job=\"$job\", env=\"$env\", thread_id=~\"$application_id.*\"}",
       "legendFormat": "File - {{app}} {{instance}} {{thread_id}} {{task_id}}"
      }
     ]
    }
   ]
  },
  { "title": "Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Bytes in Per Sec",
   "type": "timeseries",
   "description": "The average number of bytes per second this Kafka consumer is reading from Kafka topics.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_rate{instance=\"$instance\", job=\"$job\", env=\"$env\", client_id=~\"$application_id.*\", topic!=\"\"}",
     "legendFormat": "{{topic}} - {{client_id}}"
    }
   ]
  },
  {
   "title": "Max Consumer Lag",
   "type": "timeseries",
   "description": "The max lag of the partition",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_lag_max{instance=\"$instance\", job=\"$job\", env=\"$env\", client_id=~\"$application_id.*\", topic!=\"\"}",
     "legendFormat": "{{topic}}-{{partition}} {{instance}}"
    }
   ]
  },
  {
   "title": "Records Processed per Sec",
   "type": "timeseries",
   "description": "The average number of records per second processed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_streams_stream_task_metrics_process_rate{instance=\"$instance\", job=\"$job\", env=\"$env\", thread_id=~\"$application_id.*\"}",
     "legendFormat": "{{instance}}, task: {{task_id}}"
    }
   ]
  },
  {
   "title": "Dropped Records Total",
   "type": "timeseries",
   "description": "The total number of dropped records ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_streams_stream_task_metrics_dropped_records{instance=\"$instance\", job=\"$job\", env=\"$env\", thread_id=~\"$application_id.*\"}",
     "legendFormat": "{{instance}}, task: {{task_id}}"
    }
   ]
  },
  {
   "title": "Bytes Fetched per Request",
   "type": "timeseries",
   "description": "The average number of bytes fetched per request",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_size_avg{instance=\"$instance\", job=\"$job\", env=\"$env\", client_id=~\"$application_id.*\", topic!=\"\"}",
     "legendFormat": "{{topic}} - {{client_id}}"
    }
   ]
  },
  {
   "title": "Number of Fetch Requests per Sec",
   "type": "timeseries",
   "description": "The number of fetch requests per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_rate{instance=\"$instance\", job=\"$job\", env=\"$env\", client_id=~\"$application_id.*\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Throttle Time",
   "type": "timeseries",
   "description": "The average throttle time in ms",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_throttle_time_avg{instance=\"$instance\", job=\"$job\", env=\"$env\", client_id=~\"$application_id.*\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Fetch Latency Avg",
   "type": "timeseries",
   "description": "The average time taken for a fetch request.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_latency_avg{instance=\"$instance\", job=\"$job\", env=\"$env\", client_id=~\"$application_id.*\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  }
 ]
}