{
 "title": "Kafka Transaction Coordinator",
 "description": "Monitor Kafka Transaction Coordinator",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(kafka_connect_app_info,env)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_server_kafkaserver_brokerstate{env=\"${env}\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Transaction Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transaction Timeout Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_transaction_coordinator_metrics_transaction_timeout_count{job=\"kafka-broker\", env=\"$env\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Transaction Error Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\nkafka_server_transaction_coordinator_metrics_transaction_state_error_count{job=\"kafka-broker\", env=\"$env\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Transaction Id Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\nkafka_server_transaction_coordinator_metrics_transactional_id_count{job=\"kafka-broker\", env=\"$env\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Timeout Rate",
   "type": "timeseries",
   "description": "The rate at which transactions are timed out by the coordinator",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_server_transaction_coordinator_metrics_transaction_timeout_rate{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Timeout Rate",
   "type": "timeseries",
   "description": "The rate at which transactions are timed out by the coordinator",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_server_transaction_coordinator_metrics_transaction_timeout_rate{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Transaction Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Open Transaction Max Time",
   "type": "timeseries",
   "description": "The max time a currently-open transaction has been open",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_server_transaction_coordinator_metrics_active_transaction_total_time_max{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "From  PrepareCommit to CompleteCommit Avg Time",
   "type": "timeseries",
   "description": "The avg time it took for a transaction to transit from PrepareCommit to CompleteCommit state in the last 30sec",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_server_transaction_coordinator_metrics_prepare_commit_to_complete_commit_latency{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Transaction Partitions (__transaction_state)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true
  },
  {
   "title": "Partitions owned by tx coordinator",
   "type": "timeseries",
   "description": "The total size of the partitions owned by the transaction coordinator",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_server_transaction_coordinator_metrics_partitions_total_size{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Time to load partitions by tx coordinator",
   "type": "timeseries",
   "description": "The max time it took to load the partitions in the last 30sec",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_server_transaction_coordinator_metrics_partition_load_time_max{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg Time to load partitions by tx coordinator",
   "type": "timeseries",
   "description": "The avg time it took to load the partitions in the last 30sec",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_server_transaction_coordinator_metrics_partition_load_time_avg{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}