{
 "title": "Kafka Quotas",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": "label_values(env)" },
   {
    "name": "broker_id",
    "label": "Broker Id",
    "query": "label_values(kafka_server_kafkaserver_brokerstate, instance)"
   },
   { "name": "client_id", "label": "Client Id", "query": "label_values(client_id)" }
  ]
 },
 "panels": [
  {
   "title": "Produce Byte Rate",
   "type": "graph",
   "description": "Indicates the data produce rate of the client in bytes/sec",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_server_produce_byte_rate{client_id=~\"$client_id\",instance=~\"$broker_id\",env=\"$env\",job=\"kafka-broker\"}"
    }
   ]
  },
  {
   "title": "Fetch Byte Rate",
   "type": "graph",
   "description": "Indicates the data consume rate of the client in bytes/sec",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_server_fetch_byte_rate{client_id=~\"$client_id\",instance=~\"$broker_id\",env=\"$env\",job=\"kafka-broker\"}"
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "graph",
   "description": "Indicates the percentage of time spent in broker network and I/O threads to process requests from client group",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kafka_server_request_request_time{client_id=~\"$client_id\",instance=~\"$broker_id\",env=\"$env\",job=\"kafka-broker\"}"
    }
   ]
  },
  {
   "title": "Produce Bandwidth Throttle",
   "type": "graph",
   "description": "Indicates the amount of time in ms the client was throttled",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_server_produce_throttle_time{client_id=~\"$client_id\",instance=~\"$broker_id\",env=\"$env\",job=\"kafka-broker\"}"
    }
   ]
  },
  {
   "title": "Fetch Bandwidth Throttle",
   "type": "graph",
   "description": "Indicates the amount of time in ms the client was throttled",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_server_fetch_throttle_time{client_id=~\"$client_id\",instance=~\"$broker_id\",env=\"$env\",job=\"kafka-broker\"}"
    }
   ]
  },
  {
   "title": "Request Throttle",
   "type": "graph",
   "description": "Indicates the amount of time in ms the client was throttled",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_server_request_throttle_time{client_id=~\"$client_id\",instance=~\"$broker_id\",env=\"$env\",job=\"kafka-broker\"}"
    }
   ]
  }
 ]
}