{
 "title": "Kafka Rest Proxy",
 "description": "Monitor Apache Kafka Connect",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(kafka_connect_app_info,env)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_rest_jersey_metrics_brokers_list_v2_request_byte_rate{job=\"rest-proxy\", env=\"$env\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connections Active",
   "type": "stat",
   "description": "Total number of active TCP connections",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_rest_jetty_metrics_connections_active{job=\"rest-proxy\", env=\"$env\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Busy Threads Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_rest_jetty_metrics_busy_thread_count{job=\"rest-proxy\", env=\"$env\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Threads Pool Usage %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_rest_jetty_metrics_thread_pool_usage{job=\"rest-proxy\", env=\"$env\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Request Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_rest_jetty_metrics_request_queue_size{job=\"rest-proxy\", env=\"$env\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connections Opened Rate per sec",
   "type": "timeseries",
   "description": "The average rate per second of opened TCP connections",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_rest_jetty_metrics_connections_opened_rate{job=\"rest-proxy\", env=\"$env\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connections Closed Rate per sec",
   "type": "timeseries",
   "description": "The average rate per second of closed TCP connections",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_rest_jetty_metrics_connections_closed_rate{job=\"rest-proxy\", env=\"$env\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connections Accepted Rate per sec",
   "type": "timeseries",
   "description": "The average rate per second of accepted TCP connections",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_rest_jetty_metrics_connections_accepted_rate{job=\"rest-proxy\", env=\"$env\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"rest-proxy\",env=\"$env\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{kafka_connect_cluster_id}}-{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"rest-proxy\",env=\"$env\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "jvm_memory_bytes_max{job=\"rest-proxy\",env=\"$env\",instance=~\"$instance\",area=\"heap\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM GC time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"rest-proxy\",env=\"$env\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Request Byte Rate",
   "type": "graph",
   "description": "Bytes/second of incoming requests",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_rest_jersey_metrics_brokers_list_v2_request_byte_rate{job=\"rest-proxy\", env=\"$env\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}} - {{instance}}"
    },
    {
     "expr": "kafka_rest_jersey_metrics_consumer_assign_v2_request_byte_rate{job=\"rest-proxy\", env=\"$env\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}} - {{instance}}"
    },
    {
     "expr": "kafka_rest_jersey_metrics_consumer_assignment_v2_request_byte_rate{job=\"rest-proxy\", env=\"$env\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}} - {{instance}}"
    },
    {
     "expr": "kafka_rest_jersey_metrics_consumer_commit_offsets_v2_request_byte_rate{job=\"rest-proxy\", env=\"$env\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}} - {{instance}}"
    },
    {
     "expr": "kafka_rest_jersey_metrics_consumer_committed_offsets_v2_request_byte_rate{job=\"rest-proxy\", env=\"$env\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}} - {{instance}}"
    },
    {
     "expr": "kafka_rest_jersey_metrics_consumer_create_v2_request_byte_rate{job=\"rest-proxy\", env=\"$env\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}} - {{instance}}"
    },
    {
     "expr": "kafka_rest_jersey_metrics_consumer_delete_v2_request_byte_rate{job=\"rest-proxy\", env=\"$env\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}} - {{instance}}"
    },
    {
     "expr": "kafka_rest_jersey_metrics_consumer_records_read_avro_v2_request_byte_rate{job=\"rest-proxy\", env=\"$env\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}} - {{instance}}"
    },
    {
     "expr": "kafka_rest_jersey_metrics_consumer_records_read_binary_v2_request_byte_rate{job=\"rest-proxy\", env=\"$env\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}} - {{instance}}"
    },
    {
     "expr": "kafka_rest_jersey_metrics_consumer_records_read_json_v2_request_byte_rate{job=\"rest-proxy\", env=\"$env\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}} - {{instance}}"
    },
    {
     "expr": "kafka_rest_jersey_metrics_consumer_records_read_jsonschema_v2_request_byte_rate{job=\"rest-proxy\", env=\"$env\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}} - {{instance}}"
    },
    {
     "expr": "kafka_rest_jersey_metrics_consumer_records_read_protobuf_v2_request_byte_rate{job=\"rest-proxy\", env=\"$env\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}} - {{instance}}"
    },
    {
     "expr": "kafka_rest_jersey_metrics_consumer_seek_to_beginning_v2_request_byte_rate{job=\"rest-proxy\", env=\"$env\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}} - {{instance}}"
    },
    {
     "expr": "kafka_rest_jersey_metrics_consumer_seek_to_end_v2_request_byte_rate{job=\"rest-proxy\", env=\"$env\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}} - {{instance}}"
    },
    {
     "expr": "kafka_rest_jersey_metrics_consumer_seek_to_offset_v2_request_byte_rate{job=\"rest-proxy\", env=\"$env\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}} - {{instance}}"
    },
    {
     "expr": "kafka_rest_jersey_metrics_consumer_subscribe_v2_request_byte_rate{job=\"rest-proxy\", env=\"$env\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}} - {{instance}}"
    },
    {
     "expr": "kafka_rest_jersey_metrics_consumer_subscription_v2_request_byte_rate{job=\"rest-proxy\", env=\"$env\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}} - {{instance}}"
    },
    {
     "expr": "kafka_rest_jersey_metrics_consumer_unsubscribe_v2_request_byte_rate{job=\"rest-proxy\", env=\"$env\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}} - {{instance}}"
    },
    {
     "expr": "kafka_rest_jersey_metrics_partition_get_v2_request_byte_rate{job=\"rest-proxy\", env=\"$env\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}} - {{instance}}"
    },
    {
     "expr": "kafka_rest_jersey_metrics_partition_produce_avro_v2_request_byte_rate{job=\"rest-proxy\", env=\"$env\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}} - {{instance}}"
    }
   ]
  }
 ]
}