{
 "title": "Zookeeper cluster",
 "description": "Overview of the Zookeeper cluster",
 "tags": [
  "confluent",
  "kafka",
  "zookeeper"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": "label_values(env)" },
   {
    "name": "zk_server",
    "label": "Server",
    "query": "label_values(zookeeper_outstandingrequests{env=\"$env\"}, hostname)"
   },
   {
    "name": "quantile",
    "label": "Quantile",
    "query": "label_values(kafka_server_zookeeperclientmetrics_zookeeperrequestlatencyms{env=\"$env\"}, quantile)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ZK: Quorum Size",
   "type": "stat",
   "description": "Quorum Size of Zookeeper ensemble.\n            Count Zookeeper servers with quorum size metric.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(zookeeper_status_quorumsize{env=\"$env\"})"
    }
   ]
  },
  {
   "title": "ZK: ZNodes (avg.)",
   "type": "stat",
   "description": "Average size of ZNodes in the cluster.\n            Getting the node count per server, and averaging the node count.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(zookeeper_inmemorydatatree_nodecount{env=\"$env\"})"
    }
   ]
  },
  {
   "title": "ZK: Connections used",
   "type": "stat",
   "description": "Sum of the number of alive connections per servers divided by the maximum number of client connections allowed per host.\n            If the percentage is higher than 60%, then Zookeeper should be scaled and/or the Zookeeper clients should be investigated to find the reason for high number of connections opened.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "zookeeper_numaliveconnections{env=\"$env\"} / zookeeper_maxclientcnxnsperhost{env=\"$env\"}"
    }
   ]
  },
  {
   "title": "ZK: Sum of watchers",
   "type": "stat",
   "description": "Sum of client watchers subscribed to changes on the ZNodes.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(zookeeper_inmemorydatatree_watchcount{env=\"$env\"})"
    }
   ]
  },
  {
   "title": "ZK: Outstanding Requests",
   "type": "timeseries",
   "description": "Number of requests waiting for processing (queued).\n            If the number of outstanding requests grows higher than 10, then the Zookeeper hosts should be checked.\n            It could mean that there is not enough resources to cope with the number of requests.\n            ",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "zookeeper_outstandingrequests{env=\"$env\"}",
     "legendFormat": "{{hostname}} ({{server_id}}:{{member_type}})"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{env=\"$env\",hostname=~\"$zk_server\"}[5m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{env=\"$env\",hostname=\"$zk_server\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "GC collection",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(gc)(irate(jvm_gc_collection_seconds_sum{env=\"$env\",hostname=\"$zk_server\"}[5m]))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Server Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "ZK: Request Latency (Minimum)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "zookeeper_minrequestlatency{env=\"$env\"} * zookeeper_ticktime",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "ZK: Request Latency (Average)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "zookeeper_avgrequestlatency{env=\"$env\"} * zookeeper_ticktime",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "ZK: Request Latency (Maximum)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "zookeeper_maxrequestlatency{env=\"$env\"} * zookeeper_ticktime",
       "legendFormat": "{{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Client Latency (Kafka)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka: Request Latency",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_server_zookeeperclientmetrics_zookeeperrequestlatencyms{env=\"$env\",quantile=~\"$quantile\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Kafka: Sync Connections/sec",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_server_sessionexpirelistener_zookeepersyncconnectspersec{env=\"$env\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Kafka: Expired Connections/sec",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_server_sessionexpirelistener_zookeeperexpirespersec{env=\"$env\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Kafka: Disconnected Connections/sec",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_server_sessionexpirelistener_zookeeperdisconnectspersec{env=\"$env\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Kafka: Auth Failures on Connections/sec",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_server_sessionexpirelistener_zookeeperauthfailurespersec{env=\"$env\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    }
   ]
  }
 ]
}