apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  name: sm-connect
spec:
  endpoints:
    - port: prometheus
      metricRelabelings:
        # remove duplicate metrics
        - regex: connect-.*
          sourceLabels: [service]
          action: drop
        # set job label
        - targetLabel: job
          replacement: kafka-connect
          action: replace
        # set env label
        - targetLabel: env
          replacement: dev
          action: replace
        # set kafka_connect_cluster_id label
        - targetLabel: kafka_connect_cluster_id
          replacement: cluster1
          action: replace
  selector:
    matchLabels:
      cr-name: connect