// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace io.confluent.demos.common.wiki
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class KsqlDataSourceSchema_META : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""KsqlDataSourceSchema_META"",""namespace"":""io.confluent.demos.common.wiki"",""fields"":[{""name"":""domain"",""default"":null,""type"":[""null"",""string""]},{""name"":""dt"",""default"":null,""type"":[""null"",""long""]},{""name"":""ID"",""default"":null,""type"":[""null"",""string""]},{""name"":""REQUEST_ID"",""default"":null,""type"":[""null"",""string""]},{""name"":""STREAM"",""default"":null,""type"":[""null"",""string""]},{""name"":""uri"",""default"":null,""type"":[""null"",""string""]}]}");
		private string _domain;
		private System.Nullable<System.Int64> _dt;
		private string _ID;
		private string _REQUEST_ID;
		private string _STREAM;
		private string _uri;
		public virtual Schema Schema
		{
			get
			{
				return KsqlDataSourceSchema_META._SCHEMA;
			}
		}
		public string domain
		{
			get
			{
				return this._domain;
			}
			set
			{
				this._domain = value;
			}
		}
		public System.Nullable<System.Int64> dt
		{
			get
			{
				return this._dt;
			}
			set
			{
				this._dt = value;
			}
		}
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				this._ID = value;
			}
		}
		public string REQUEST_ID
		{
			get
			{
				return this._REQUEST_ID;
			}
			set
			{
				this._REQUEST_ID = value;
			}
		}
		public string STREAM
		{
			get
			{
				return this._STREAM;
			}
			set
			{
				this._STREAM = value;
			}
		}
		public string uri
		{
			get
			{
				return this._uri;
			}
			set
			{
				this._uri = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.domain;
			case 1: return this.dt;
			case 2: return this.ID;
			case 3: return this.REQUEST_ID;
			case 4: return this.STREAM;
			case 5: return this.uri;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.domain = (System.String)fieldValue; break;
			case 1: this.dt = (System.Nullable<System.Int64>)fieldValue; break;
			case 2: this.ID = (System.String)fieldValue; break;
			case 3: this.REQUEST_ID = (System.String)fieldValue; break;
			case 4: this.STREAM = (System.String)fieldValue; break;
			case 5: this.uri = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
