// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace io.confluent.demos.common.wiki
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class WikiEdit : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"WikiEdit\",\"namespace\":\"io.confluent.demos.common.wiki\",\"" +
				"fields\":[{\"name\":\"bot\",\"default\":null,\"type\":[\"null\",\"boolean\"]},{\"name\":\"commen" +
				"t\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"id\",\"default\":null,\"type\":[" +
				"\"null\",\"long\"]}]}");
		private System.Nullable<System.Boolean> _bot;
		private string _comment;
		private System.Nullable<System.Int64> _id;
		
		public virtual Schema Schema
		{
			get
			{
				return WikiEdit._SCHEMA;
			}
		}
		public System.Nullable<System.Boolean> bot
		{
			get
			{
				return this._bot;
			}
			set
			{
				this._bot = value;
			}
		}
		public string comment
		{
			get
			{
				return this._comment;
			}
			set
			{
				this._comment = value;
			}
		}
		public System.Nullable<System.Int64> id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.bot;
			case 1: return this.comment;
			case 2: return this.id;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.bot = (System.Nullable<System.Boolean>)fieldValue; break;
			case 1: this.comment = (System.String)fieldValue; break;
			case 2: this.id = (System.Nullable<System.Int64>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
