version: "2.3"
services:
  zookeeper:
    volumes:
      - $MONITORING_STACK/../shared-assets/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      EXTRA_ARGS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.20.0.jar=1234:/usr/share/jmx-exporter/zookeeper.yml

  kafka1:
    volumes:
      - $MONITORING_STACK/../shared-assets/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      EXTRA_ARGS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.20.0.jar=1234:/usr/share/jmx-exporter/kafka_broker.yml

  kafka2:
    volumes:
      - $MONITORING_STACK/../shared-assets/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      EXTRA_ARGS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.20.0.jar=1234:/usr/share/jmx-exporter/kafka_broker.yml

  streams-demo:
    volumes:
      - $MONITORING_STACK/../shared-assets/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      JAVA_OPTS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.20.0.jar=1234:/usr/share/jmx-exporter/kafka_streams.yml

  connect:
    volumes:
      - $MONITORING_STACK/../shared-assets/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      EXTRA_ARGS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.20.0.jar=1234:/usr/share/jmx-exporter/kafka_connect.yml

  schemaregistry:
    volumes:
      - $MONITORING_STACK/../shared-assets/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      EXTRA_ARGS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.20.0.jar=1234:/usr/share/jmx-exporter/confluent_schemaregistry.yml

  ksqldb-server:
    volumes:
      - $MONITORING_STACK/../shared-assets/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      KSQL_OPTS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.20.0.jar=1234:/usr/share/jmx-exporter/confluent_ksql.yml

  restproxy:
    volumes:
      - $MONITORING_STACK/../shared-assets/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      KAFKAREST_OPTS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.20.0.jar=1234:/usr/share/jmx-exporter/confluent_rest.yml

  node-exporter:
    image: prom/node-exporter:v1.2.2
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points"
      - "^(aufs|proc|nsfs|shm|cgroup|tmpfs|binfmt_misc|debugfs|devpts|fusectl|hugetlbfs|fuse.lxcfs|mqueue|pstore|securityfs|sysfs|autofs|devtmpfs|configfs)"

  kafka-lag-exporter:
    image: seglo/kafka-lag-exporter:0.7.1
    container_name: kafka-lag-exporter
    hostname: kafka-lag-exporter
    restart: always
    volumes:
      - $MONITORING_STACK/../shared-assets/kafka-lag-exporter:/opt/docker/conf
      - $MONITORING_STACK/assets/security:/etc/kafka/secrets

  newrelic:
    image: newrelic/nri-prometheus:2.18
    container_name: nri-prometheus
    restart: unless-stopped
    environment:
      - LICENSE_KEY=$MONITORING_KEY
    volumes:
      - $MONITORING_STACK/assets/newrelic/config.yaml:/config.yaml