services:
  minio:
    image: minio/minio
    hostname: minio
    container_name: minio
    profiles:
      - tieredstorage
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data

  kafka1:
    depends_on:
      - minio
    environment:
      KAFKA_CONFLUENT.TIER.FEATURE: true
      KAFKA_CONFLUENT.TIER.ENABLE: true
      KAFKA_CONFLUENT.TIER.BACKEND: S3
      KAFKA_CONFLUENT.TIER.S3.BUCKET: democp-bucket
      KAFKA_CONFLUENT.TIER.S3.REGION: us-east-1
      KAFKA_CONFLUENT.TIER.S3.AWS.ENDPOINT.OVERRIDE: http://minio:9000
      KAFKA_CONFLUENT.TIER.S3.FORCE.PATH.STYLE.ACCESS: true
      KAFKA_CONFLUENT.TIER.S3.CRED.FILE.PATH: /tmp/minio.properties
    volumes:
      - $PWD/tieredstorage/minio.properties:/tmp/minio.properties

  kafka2:
    depends_on:
      - minio
    environment:
      KAFKA_CONFLUENT.TIER.FEATURE: true
      KAFKA_CONFLUENT.TIER.ENABLE: true
      KAFKA_CONFLUENT.TIER.BACKEND: S3
      KAFKA_CONFLUENT.TIER.S3.BUCKET: democp-bucket
      KAFKA_CONFLUENT.TIER.S3.REGION: us-east-1
      KAFKA_CONFLUENT.TIER.S3.AWS.ENDPOINT.OVERRIDE: http://minio:9000
      KAFKA_CONFLUENT.TIER.S3.FORCE.PATH.STYLE.ACCESS: true
      KAFKA_CONFLUENT.TIER.S3.CRED.FILE.PATH: /tmp/minio.properties
    volumes:
      - $PWD/tieredstorage/minio.properties:/tmp/minio.properties

  kafka3:
    depends_on:
      - minio
    environment:
      KAFKA_CONFLUENT.TIER.FEATURE: true
      KAFKA_CONFLUENT.TIER.ENABLE: true
      KAFKA_CONFLUENT.TIER.BACKEND: S3
      KAFKA_CONFLUENT.TIER.S3.BUCKET: democp-bucket
      KAFKA_CONFLUENT.TIER.S3.REGION: us-east-1
      KAFKA_CONFLUENT.TIER.S3.AWS.ENDPOINT.OVERRIDE: http://minio:9000
      KAFKA_CONFLUENT.TIER.S3.FORCE.PATH.STYLE.ACCESS: true
      KAFKA_CONFLUENT.TIER.S3.CRED.FILE.PATH: /tmp/minio.properties
    volumes:
      - $PWD/tieredstorage/minio.properties:/tmp/minio.properties

  kafka4:
    depends_on:
      - minio
    environment:
      KAFKA_CONFLUENT.TIER.FEATURE: true
      KAFKA_CONFLUENT.TIER.ENABLE: true
      KAFKA_CONFLUENT.TIER.BACKEND: S3
      KAFKA_CONFLUENT.TIER.S3.BUCKET: democp-bucket
      KAFKA_CONFLUENT.TIER.S3.REGION: us-east-1
      KAFKA_CONFLUENT.TIER.S3.AWS.ENDPOINT.OVERRIDE: http://minio:9000
      KAFKA_CONFLUENT.TIER.S3.FORCE.PATH.STYLE.ACCESS: true
      KAFKA_CONFLUENT.TIER.S3.CRED.FILE.PATH: /tmp/minio.properties
    volumes:
      - $PWD/tieredstorage/minio.properties:/tmp/minio.properties




volumes:
  minio_storage: {}