{
 "title": "ksqldb Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "env",
    "query": "label_values(ksql_ksql_engine_query_stats_liveness_indicator,env)"
   },
   {
    "name": "clusterid",
    "query": "label_values(ksql_ksql_engine_query_stats_liveness_indicator,ksql_cluster)"
   },
   {
    "name": "instance",
    "query": "label_values(ksql_ksql_engine_query_stats_liveness_indicator,instance)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster liveness",
   "type": "graph",
   "description": "Cluster liveness",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ksql_ksql_engine_query_stats_liveness_indicator{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$clusterid\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Num of persisted queries",
   "type": "singlestat",
   "description": "Num of persisted queries",
   "gridPos": { "h": 4, "w": 6, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ksql_ksql_engine_query_stats_num_persistent_queries{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$clusterid\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Num of active queries",
   "type": "singlestat",
   "description": "Num of active queries",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ksql_ksql_engine_query_stats_num_active_queries{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$clusterid\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Num of idle queries",
   "type": "singlestat",
   "description": "Num of idle queries",
   "gridPos": { "h": 4, "w": 6, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ksql_ksql_engine_query_stats_num_idle_queries{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$clusterid\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Num of created queries",
   "type": "singlestat",
   "description": "Num of created queries",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ksql_ksql_engine_query_stats_created_queries{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$clusterid\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Num of running queries",
   "type": "singlestat",
   "description": "Num of created queries",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ksql_ksql_engine_query_stats_running_queries{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$clusterid\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Num of error query",
   "type": "singlestat",
   "description": "Number of error query",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ksql_ksql_engine_query_stats_error_queries{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$clusterid\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Num of not running queries",
   "type": "singlestat",
   "description": "Num of not running queries",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ksql_ksql_engine_query_stats_not_running_queries{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$clusterid\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Num of pending shutdown query",
   "type": "singlestat",
   "description": "Num of running queries",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ksql_ksql_engine_query_stats_pending_shutdown_queries{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$clusterid\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Num of rebalancing queries",
   "type": "singlestat",
   "description": "Num of rebalancing queries",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ksql_ksql_engine_query_stats_rebalancing_queries{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$clusterid\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Message produced/sec",
   "type": "graph",
   "description": "Message produced/sec",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ksql_ksql_engine_query_stats_messages_produced_per_sec{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$clusterid\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Message consumed/sec",
   "type": "graph",
   "description": "Message consumed/sec",
   "gridPos": { "h": 6, "w": 11, "x": 10, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ksql_ksql_engine_query_stats_messages_consumed_per_sec{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$clusterid\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Queries Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Queries Status",
   "type": "table",
   "gridPos": { "h": 16, "w": 7, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "ksql_ksql_metrics_ksql_queries_query_status{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$clusterid\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Poll Latency (Max + Avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_poll_latency_avg{job=\"ksqldb\", env=\"$env\", thread_id=~\".+$clusterid.+\", instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}_avg"
    },
    {
     "expr": "kafka_streams_stream_thread_metrics_poll_latency_max{job=\"ksqldb\", env=\"$env\", thread_id=~\".+$clusterid.+\", instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}_max"
    },
    {}
   ]
  },
  {
   "title": "Process Latency (Max + Avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_producer_node_metrics_request_latency_avg{job=\"ksqldb\", env=\"$env\", client_id=~\".+$clusterid.+\", instance=~\"$instance\"}",
     "legendFormat": "{{client_id}}_avg"
    },
    {
     "expr": "kafka_producer_producer_node_metrics_request_latency_max{job=\"ksqldb\", env=\"$env\", client_id=~\".+$clusterid.+\", instance=~\"$instance\"}",
     "legendFormat": "{{client_id}}_max"
    }
   ]
  },
  {
   "title": "Commit Latency (Max + Avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_commit_latency_avg{job=\"ksqldb\", env=\"$env\", thread_id=~\".+$clusterid.+\", instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}_avg"
    },
    {
     "expr": "kafka_streams_stream_thread_metrics_commit_latency_max{job=\"ksqldb\", env=\"$env\", thread_id=~\".+$clusterid.+\", instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}_max"
    }
   ]
  },
  {
   "title": "Punctuate Latency (Max + Avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_request_latency_avg{job=\"ksqldb\", env=\"$env\", client_id=~\".+$clusterid.+\", instance=~\"$instance\"}",
     "legendFormat": "{{client_id}}_avg"
    },
    {
     "expr": "kafka_producer_producer_metrics_request_latency_max{job=\"ksqldb\", env=\"$env\", client_id=~\".+$clusterid.+\", instance=~\"$instance\"}",
     "legendFormat": "{{client_id}}_max"
    }
   ]
  },
  {
   "title": "Hosting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"ksqldb\", env=\"$env\", instance=~\"$instance\"}[5m])*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"ksqldb\", env=\"$env\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"ksqldb\", env=\"$env\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}