version: "2.3"
services:
  zookeeper:
    volumes:
      - $MONITORING_STACK/assets/prometheus/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      EXTRA_ARGS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.12.0.jar=1234:/usr/share/jmx-exporter/zookeeper.yml

  kafka1:
    volumes:
      - $MONITORING_STACK/assets/prometheus/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      EXTRA_ARGS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.12.0.jar=1234:/usr/share/jmx-exporter/kafka_broker.yml

  kafka2:
    volumes:
      - $MONITORING_STACK/assets/prometheus/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      EXTRA_ARGS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.12.0.jar=1234:/usr/share/jmx-exporter/kafka_broker.yml

  streams-demo:
    volumes:
      - $MONITORING_STACK/assets/prometheus/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      JAVA_OPTS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.12.0.jar=1234:/usr/share/jmx-exporter/kafka_streams.yml

  connect:
    volumes:
      - $MONITORING_STACK/assets/prometheus/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      EXTRA_ARGS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.12.0.jar=1234:/usr/share/jmx-exporter/kafka_connect.yml

  schemaregistry:
    volumes:
      - $MONITORING_STACK/assets/prometheus/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      EXTRA_ARGS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.12.0.jar=1234:/usr/share/jmx-exporter/confluent_schemaregistry.yml

  ksqldb-server:
    volumes:
      - $MONITORING_STACK/assets/prometheus/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      KSQL_OPTS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.12.0.jar=1234:/usr/share/jmx-exporter/confluent_ksql.yml

  restproxy:
    volumes:
      - $MONITORING_STACK/assets/prometheus/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      KAFKAREST_OPTS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.12.0.jar=1234:/usr/share/jmx-exporter/confluent_rest.yml

  prometheus:
    image: prom/prometheus:v2.11.1
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - $MONITORING_STACK/assets/prometheus/prometheus-config/:/etc/prometheus/

  node-exporter:
    image: prom/node-exporter:v0.18.1
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points"
      - "^(aufs|proc|nsfs|shm|cgroup|tmpfs|binfmt_misc|debugfs|devpts|fusectl|hugetlbfs|fuse.lxcfs|mqueue|pstore|securityfs|sysfs|autofs|devtmpfs|configfs)"

  kafka-lag-exporter:
    image: lightbend/kafka-lag-exporter:0.5.5
    container_name: kafka-lag-exporter
    hostname: kafka-lag-exporter
    restart: always
    volumes:
      - $MONITORING_STACK/assets/prometheus/kafka-lag-exporter:/opt/docker/conf
      - $MONITORING_STACK/assets/prometheus/security:/etc/kafka/secrets

  grafana:
    image: grafana/grafana:7.0.6
    container_name: grafana
    environment:
      - "GF_INSTALL_PLUGINS=grafana-piechart-panel"
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_ADMIN_PASSWORD=password"
      - "GF_USERS_ALLOW_SIGN_UP=false"
    ports:
      - 3000:3000
    volumes:
      - $MONITORING_STACK/assets/prometheus/grafana/provisioning/:/etc/grafana/provisioning/
